### ISSUE TITLE
PFP09 某商业项目申请压测资助

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#10]
项目冷启动，需要建立用户钱包以及做真实用户压测，申请50万SWTC

**Comment by Yelvabaoji** [comment]
这个信息太少了点。

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=3DD0AD16E74B9776E8A49A3D6840639C07CCC631864F662DDD62FB7594CB7DC5&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
