### ISSUE TITLE
PFP10 区块链数据app

### ISSUE THREAD

**Issue by qukuaibaba** [JCCDex/ProjectFundingProposal#11]
能登录挖矿信息
接受挖矿地址
展示链接状态
当前区块号
节点详情，自动获取，能获取自己钱包剩余币的余额，能够转发自己的货币给别人，一键转发，能提供安卓，苹果下载，能够开起节点，关闭节点

**Comment by AnFengDe** [comment]
你是提需求的，还是要自己开发？开发，请列出工作量清单啊

**Comment by qukuaibaba** [comment]
> 你是提需求的，还是要自己开发？开发，请列出工作量清单啊

开发的，找人融资开发，预算1w

**Comment by qukuaibaba** [comment]
> 你是提需求的，还是要自己开发？开发，请列出工作量清单啊

找人合作开发，希望融资1w，开源的

**Comment by qukuaibaba** [comment]
> 你是提需求的，还是要自己开发？开发，请列出工作量清单啊

找人合作开发开源的，希望融资1w，

**Comment by AnFengDe** [comment]
好呀，问题是技术委员会是基于你的工作清单评估的，没有工作清单，难以评估项目的投资范围啊

**Comment by qukuaibaba** [comment]
> 好呀，问题是技术委员会是基于你的工作清单评估的，没有工作清单，难以评估项目的投资范围啊


上面不是列举了功能吗，做出来就行了，对于区块链来说都是很有用的功能，可以开源投入使用的，为什么要怎么局限于清单，项目你们觉得可以，觉得对你们有用，就可以找人开发出来对接任何平台，得到的价值大于它就行了

**Comment by AnFengDe** [comment]
请参考下其他的issue，让技术人员评估工作量，这个是不够的，太粗糙了

**Comment by AnFengDe** [comment]
568285439 去加这个QQ群，在群里广播，找码农吧

**Comment by Yelvabaoji** [comment]
QuKuaibaba, 这个你有后续的跟进吗？比如说，更详细的描述？
