### ISSUE TITLE
PFP11 井通区块链学习大纲：历程，情况和案例

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#12]
- [ ] 区块链的发展历程
- [ ] 区块链行业当前情况
- [ ] 区块链技术运用典型案例

**Comment by anything33** [comment]
一、区块链的发展历程
.什么是区块链
.区块链的形式
.区块链的核心
.区块链的特点
.区块链的起源与发展
二、区块链行业当前情况
.区块链行业前景
.当前区块链的核心问题：应用于落地
.当前行业亟待解决的问题
以上DOC+PPT 图+文字编辑
估算3-4个工作日

**Comment by xdjiang** [comment]
区块链不能简单定义为分布式数据库

**Comment by bbbooo313** [comment]
ouboheiqian.com  【链圈】大佬换个友链吗？
联系QQ：1297532431

**Comment by anything33** [comment]
[区块链的发展历程.docx](https://github.com/JCCDex/ProjectFundingProposal/files/3640416/default.docx)
[区块链的发展历程.pptx](https://github.com/JCCDex/ProjectFundingProposal/files/3640417/default.pptx)
[区块链行业当前情况.pptx](https://github.com/JCCDex/ProjectFundingProposal/files/3640418/default.pptx)
[区块链行业的当前情况.docx](https://github.com/JCCDex/ProjectFundingProposal/files/3640419/default.docx)

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=BD8E7C6E0276E4F35A4FF4FD367C32DD161ED7DDEA426A1D94A8C8A7360EAADE&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
