### ISSUE TITLE
PFP13 井通区块链学习大纲：井通区块链开发概念

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#14]
- [ ] 井通区块链的基本概念
- [ ] 井通区块链的开发方向
- [ ] 井通区块链开发概要
- [ ] 井通区块链开发流程

**Comment by AnFengDe** [comment]
标题太多，讲清楚井通区块链和其他区块链差别，机制，以及定位就行

系统架构图，显示出不同层次开发的位置

3-5天

**Comment by bbbooo313** [comment]
www.qukuailianquanzi.com  【链圈】大佬换个友链吗？
联系QQ：1297532431

**Comment by xdjiang** [comment]
1:开发概要与PFP13内容重合
2:缺少开发流程介绍和开发注意事项
3:技术简介可以删除
