### ISSUE TITLE
PFP14 井通区块链学习大纲：SWTCLIB / JINGTUMLIB

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#15]
社区的包是 swtclib

井通官方包是 jingtumlib

从access blockchain的角度出发，一步步介绍核心接口

* 搞个钱包玩玩
* 激活转账：节点，燃料，hash概念和如何使用
* 通证的转账
* 本地签名和不签名的玩法
* 井通的交易挂单是加强属性了

不同lib的异同，哪个牛，开发者自己喷吧

以上有示例，有PPT，有解说文字，估算范围10-20个工数

**Comment by wudanjs** [comment]
1.标题不知道能不能修改，如果能修改，加上jingtumlib吧；
2.核心接口这里最好把【账本信息】、【交易信息】及【合约功能】也能说明下。

**Comment by lospringliu** [comment]
### 粗略估计 总20工时
1. 一个自动激活的水管API, 提供自动化的激活和cny测试通证
> #### 跑测试网
> #### 部署到免费云中作为公共服务
> #### 3 工时
2. 一个基于网页的swtclib的实时互动式教程 （jingtumlib已包含，以标签方式标注独有接口）
> #### 基于标签的知识点过滤
> #### 采用vuetify的card + modal界面
> #### 浏览器运行时
> #### 10 工时
3. ppt教程， 修改互动式教程
> #### 3 工时
4. 测试，调试，修正
> #### 4 工时

**Comment by AnFengDe** [comment]
20个工时？小时不是人天？你这个按照小时计算，太少了吧，光写PPT 20个小时也不够啊？

**Comment by AnFengDe** [comment]
@wudanjs 你的jingtum lib的相关，请给一个估计工数

**Comment by wudanjs** [comment]
**jingtum-lib教程粗略估计19人日**
1. PPT教程  3人日
2. 一个基于网页的jingtum-lib实时互动演示系统  12人日
3. 调试、修正  4人日

**Comment by lospringliu** [comment]
已更新进展和粗估

**Comment by xdjiang** [comment]
1:ppt里缺少撤单例子
2:缺少本地签名和非本地签名的例子

**Comment by wudanjs** [comment]
> 1:ppt里缺少撤单例子
> 2:缺少本地签名和非本地签名的例子

已更正。

**Comment by AnFengDe** [comment]
[lospringliu支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=C1FFED54049EB7C8DB1C8024188A39684D66E6492C3C99FDFD33656956229B04&wallet=j3vyFAMQW2Ls48eoFCTsMXFq2KNWVUskSx)
