### ISSUE TITLE
PFP15 井通区块链学习大纲：JCC_RPC服务

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#16]
* 为什么用RPC，不直接玩节点呢
* RPC的主要接口分类
* 使用RPC的例子：解释为什么这么做
* 意外的结果处理策略，如何保证更高的吞吐量和稳定性
* 实际RPC的例子：钱包，转账，交易
* RPC的版本有哪些，在哪些项目中使用

以上PPT,代码示例，文字说明

估算 10-20个工日

**Comment by Yelvabaoji** [comment]
请更新确切的工日

**Comment by GinMu** [comment]
10天

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=A341781EAB974DDE57AB139BD8B8A6B4D97453CB5B39FDF12CB0125A32BED6AB&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
