### ISSUE TITLE
PFP16 井通区块链学习大纲：钱包开发

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#17]

**Comment by gwang74** [comment]
井创这边正在做SWTC的钱包，这个文档我们应该可以做，通过这个正好可以整理下自己的成果^_^。

<table>
<tr>
    <td style="width: 100px;">工作量</td>
    <td>10人日</td>
</tr>
<tr>
    <td>内容</td>
    <td>
    <li> 区块链钱包简介 </li>
    <li> 钱包基础功能介绍 </li>
    <li> 钱包余额显示 </li>
    <li> 钱包转账操作 </li>
    <li> 钱包交易历史显示 </li>
    <li> 钱包节点配置 </li>
    </td>
</tr>
</table>

目前能想到的就这些，也正是我们在做的。

**Comment by abellq** [comment]
**工作量 15人日** 
主要内容如下：
1.区块链钱包简介 
2.钱包生成 
3.钱包余额显示 
4.钱包转账操作 
5.钱包交易历史显示 
6.钱包节点配置
7.其他 
附：采用H5或者Ionic可以编译源码简单APP

**Comment by purplieee** [comment]
之前公司准备自己开发一个钱包，后期预估了下成本太高了，就用了优盾钱包，还算省时省力

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=5F51B1B53CF1927122C9F22D4ED2B1EF2DE721FEE829556BAFA2815EF63B40A0&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
