### ISSUE TITLE
PFP17 jingtum-lib Rust版本

### ISSUE THREAD

**Issue by zTgx** [JCCDex/ProjectFundingProposal#18]
名称： [jlib-rs](https://github.com/zTgx/jlib-rs.git)
简介：jingtum-lib Rust版本
Wiki：[wiki](https://github.com/zTgx/jlib-rs/wiki)
工作量:：[workloads](https://github.com/zTgx/jlib-rs/blob/master/docs/workloads.md)

**Comment by AnFengDe** [comment]
开发的目的是啥？
我迷惑的地方在于井通链的实际开发主要是
* 面向互联网的用nodejs
* 面向行业B端的用java
* 面向搬砖的用PY
APP也有java和oc的一些支持

请问这个rust用在哪，或者目的是啥？做个比nodejs更稳定效率更高的服务器版本？个人的喜好问题？
还是有客户想要？

我很愿意投赞成票，如果能告诉我你开发的目的是啥就更好了

**Comment by zTgx** [comment]
你好，先说结论，这个项目jlib-rs算是个人的爱好.
像早期的一些区块链底层大多用C++开发的，比如ripple、以太坊，后来出现一些go语言的实现，近两年出现国外出现一批基于Rust的实现像libra、substrate，国内也有一些底层是基于Rust的，加上它的学习曲线比较陡峭，相对小众，作为程序员，觉得很有挑战性，算是追赶技术潮流，于是实现了Rust版。
至于跟nodejs版的区别，我目前还没有做性能等方面的测试比较，不过据Rust官方宣称的性能是接近C++的，有一点可以肯定作为强类型的语言，包括移动语义，生命周期等特性使得Rust开发效率不是太高。俗称：出活儿慢。
：）

**Comment by lospringliu** [comment]
@zTgx , 这个是已经完成了吗？

**Comment by zTgx** [comment]
剩下process_tx方法待实现，主要涉及到交易字段的反序列化功能，其他的都已经完成了。

**Comment by Yelvabaoji** [comment]
做好了又两个要求：1，rust社区找一个人来审计（审计费可以另外出） 2，开源到rust社区去。

**Comment by zTgx** [comment]
上周已经开源到了Rust社区，并且可以在官方Package Registry下载，目前已经迭代了2个版本，具体链接在repo的README中。
关于审计，有什么标准，审计费怎么出，我好找人。

**Comment by lospringliu** [comment]
按照swtc-lib文档中的实例，把rust库中对应的也写一遍吧，这样人人都可以直接试。同时也是功能性检验。
你的文档已有，没必要重复，只出实例就行
http://swtc.daszichan.com/docs/swtclib/

**Comment by AnFengDe** [comment]
根据你提供的工数一共26周，合计130人天，6.5人月，审计一般给10%，合计7.15人月，按照这个支付

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=40EEDA359354798F1519E5EFE078D58EDA69507C0DFC9882BE50DAC6DC32EB8D&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by life-is-short-pythonn** [comment]
要py干嘛呀!写明白啊?面向搬砖什么鬼吗

**Comment by FeiPengZheng** [comment]
# jlib-rs 代码审计报告

#### 审计信息
__版本__  : ```v0.2.0  ```  
__工具__  :
```
rustc 1.37.0-nightly (8aa42ed7c 2019-06-24)
cargo 1.37.0-nightly (807429e1b 2019-06-11)
```
__审计人__: [Pfzheng](https://github.com/FeiPengZheng)

#### 审计方法  
* 代码走查及单元测试

#### 审计内容
* process_tx方法
* 涉及第三方库更新的模块basex

#### 审计结果
- [x] 方法及变量命名符合snake_case命名法
- [x] 参数使用引用方式传递，减少了拷贝开销
- [x] 变量都有缺省值
- [x] 对Result/Option变量进行了解包判断
- [x] 相关代码块进行了注释
- [x] 功能模块测试通过
- [x] basex库相关代码验证通过
- [x] examples更新成功

#### 审计建议
- [x] process_tx实现可以拆分的更小

**Comment by Yelvabaoji** [comment]
请把开放/开源到rust社区的链接发一个出来

**Comment by zTgx** [comment]
[Rust Package Registry 地址](https://crates.io/crates/jlib)

**Comment by Yelvabaoji** [comment]
能否到他们的社区，比如说 http://kriry.com/a/community/rust，然后就去放一下链接，然后就说明一下，说我做了个什么区块链的库啊什么的 （当然放一个井通的链接总归是要的：https://www.jingtum.com/）。

**Comment by zTgx** [comment]
可以的，下周会做一下这个工作。

**Comment by FeiPengZheng** [comment]
# jlib-rs 代码审计报告

#### 审计信息
__版本__  : ```v0.2.3  ```  
__工具__  :
```
rustc 1.37.0-nightly (8aa42ed7c 2019-06-24)
cargo 1.37.0-nightly (807429e1b 2019-06-11)
```
__审计人__: [Pfzheng](https://github.com/FeiPengZheng)

#### 审计方法  
* 代码走查及单元测试

#### 审计内容
* 新增 graphyql 模块
* examples 更新
* 相关bug fix

#### 审计结果
- [x] graphyql模块化实现合理
- [x] 有效的方法命名
- [x] 功能模块测试通过
- [x] examples更新成功

#### 审计建议
- [x] graphyql模块可以分离出来，依赖jlib，优化成一个API服务器

**Comment by zTgx** [comment]
v0.2.5 版本已发布。

**Comment by zTgx** [comment]
[jlib-rs](https://crates.io/crates/jlib/0.3.0) v0.3.0版本发布

**Comment by FeiPengZheng** [comment]
# jlib-rs 代码审计报告

#### 审计信息
__版本__  : ```v0.3.0  ```  
__工具__  :
```
cargo 1.38.0 (23ef9a4ef 2019-08-20)
rustc 1.38.0 (625451e37 2019-09-23)
```
__审计人__: [Pfzheng](https://github.com/FeiPengZheng)

#### 审计方法  
* 代码走查及单元测试

#### 审计内容
* 优化base模块代码
* 删除不准确的代码注释

#### 审计结果
- [x] 验证通过

**Comment by zTgx** [comment]
在 reddit rust社区发布了一个介绍的帖子， [reddit-rust地址](https://www.reddit.com/r/rust/comments/dj0qcp/a_blockchain_lib) ，国内需要科学上网。

**Comment by lospringliu** [comment]
https://github.com/zTgx/jlib-rs/pull/4 

要求提供这部分实测

**Comment by zTgx** [comment]
jlib在v0.3.0版本（10月16号），工作量已经全部完成，（目前最新版本是v0.3.1）。之前通知我说有一段时间的公示期，什么时候结束呢？
