### ISSUE TITLE
PFP20 keystore密码分布式破解工具JAVA版本开发

### ISSUE THREAD

**Issue by ApisChen** [JCCDex/ProjectFundingProposal#21]
需求分析，目前有些持币用户，特别是参与ICO等锁仓活动用户，长期持币不常使用钱包。容易忘记钱包交易密码，更有甚者会丢失钱包私钥，导致资产损失。在此背景基础上，申请开发分布式keystore破解工具，初步设计该工具具有以下功能：
* 支持设置密码规则，数字、大小写字母、特殊符号
* 支持任务中断后，从已知进度重新分配计算
* 支持多客户端分布式计算
* 支持任务进度汇总和进度、预期显示
* 支持高级的自定义表达式密码规则

技术选型
* master、slave端均采用Java语言开发
* master端采用redis内存数据库，支持高并发场景
* 采用Storm框架实现任务调度

输出
* 源代码
* slave、master端 jar安装包
* master端部署文档

工作量评估
* 预计44工作日完成

明细
* 系统框架架构
	1)Storm框架	2日
	2)redis框架	1日
	3)接口抽象	2日
* 任务分发
	1)密码生成器	2日
	2)计算任务拆分	3日
	3)计算任务分发	2日
	4)结果汇总	2日
	5)断点恢复	3日
        6)自定义密码表达式 3日
* 分布式计算
	1)keystore加密算法实现	3日
	2)拆分加密算法(slave不能反推keystore)	5日
* Master前端UI
	1)任务进度呈现	2日
	2)任务新建、撤销	2日
	3)暂停任务	3日
* 简易安装
	1)Master环境一键部署脚本	3日
	2)Master服务一键启停脚本	3日
	3)Slave端一键启动	1日
	4)Slave端GUI配置	2日

**Comment by AnFengDe** [comment]
多谢
其实我就想问，能搞到手机上跑吗，这样能召唤很多机器来加入哈，或者将slave做成一个SDK？

算啦，如果这样，工作量会增加不少的，先搞一个版本可用的吧

**Comment by xmzhou2019** [comment]
希望能够加入常用破解字典支持。或者预定义规则支持，比如说用户知道自己的口令大概是8位到10位，有一个大写字母，有一个标点符合.这样应该能够大大节约破解时间。

**Comment by ApisChen** [comment]
> 多谢
> 其实我就想问，能搞到手机上跑吗，这样能召唤很多机器来加入哈，或者将slave做成一个SDK？
> 
> 算啦，如果这样，工作量会增加不少的，先搞一个版本可用的吧

先PC版出来，Strom理论可以支持到Android版本，到时候再另外立项弄吧。

**Comment by ApisChen** [comment]
> 希望能够加入常用破解字典支持。或者预定义规则支持，比如说用户知道自己的口令大概是8位到10位，有一个大写字母，有一个标点符合.这样应该能够大大节约破解时间。

已经将此项功能加入开发计划，工作量有所变更40日--> 44日。

**Comment by ApisChen** [comment]
> > 多谢
> > 其实我就想问，能搞到手机上跑吗，这样能召唤很多机器来加入哈，或者将slave做成一个SDK？
> > 算啦，如果这样，工作量会增加不少的，先搞一个版本可用的吧
> 
> 先PC版出来，Strom理论可以支持到Android版本，到时候再另外立项弄吧。

**Comment by lospringliu** [comment]
要求必须支持到井通通墨客常用的keystore， 即weidex和TP的格式支持是必须。 验收时要跑通实测

**Comment by ApisChen** [comment]
> 要求必须支持到井通通墨客常用的keystore， 即weidex和TP的格式支持是必须。 验收时要跑通实测

可以支持，工作量评估不变。

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=98EFCF2627575B541F7C81A4B8A7E2B853DB51894D0CA04A1223BD70DD95DABD&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by ApisChen** [comment]
进度汇报：整合kafka消息队列完成，根据掩码生成密码组合的逻辑完成，keystore计算任务拆分下发(防窃取)完成60%

**Comment by lospringliu** [comment]
@ApisChen , 报一下进度

**Comment by ApisChen** [comment]
@lospringliu  目前进度约50%

**Comment by ApisChen** [comment]
目前这个月比较忙，进展还是65%。

**Comment by ApisChen** [comment]
开发完毕，源码地址：https://github.com/gaoshan-tech/happyKeystore
