### ISSUE TITLE
PFP22 墨客链投票系统

### ISSUE THREAD

**Issue by Yelvabaoji** [JCCDex/ProjectFundingProposal#23]
基于墨客主链的区块链投票系统。
投票系统的基本需求描述草稿见下面文件。
[墨客投票2.pdf](https://github.com/JCCDex/ProjectFundingProposal/files/3563437/2.pdf)

一些技术要求：
1，基于墨客链，使用墨客币
2，UI以移动端为主
3，UI需要和钱包对接，即从钱包端可以进入该工具，钱包端可以授权使用钱包账户。

**Comment by abellq** [comment]
墨客的钱包都有API可以对接起来吗？

**Comment by Yelvabaoji** [comment]
> 墨客的钱包都有API可以对接起来吗？

TP 已经有了，imoac也在规划中。
更详细的可以私聊我 - QQ：1547377535

**Comment by ApisChen** [comment]
[投票系统工作量评估.pdf](https://github.com/JCCDex/ProjectFundingProposal/files/3591976/default.pdf)
提交方案详细设计和工作量文档，不做匿名投票，因为发交易形式无法匿名。投票结束以区块号形式结束，这个是变相时间为限制，投票人数无法限制，因为投票需要一个确认时间，很容易多投票

**Comment by ApisChen** [comment]
> @ApisChen , 提几个要求。 本质上要求尽量少用数据库， 多用链上交易
> 
> 1. 要求所有的投票本身要有链上记录， 要提供记录的结构供参考
> 2. 链上记录可查， 可以还原投票内容，当然图片之类的信息就免了。 这样任何客户端都可以直接获取
> 3. 链上记录结果可验证。要求花点功夫设计一下，让验证简单

1. 会提供完整设计文档，中心化数据库、链上数据结构说明。
2. 投票信息上链，图片数据存服务器上。
3. 目前将投票信息存入inputdata中，辅助查验投票内容，但不做闭环验证。

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=64B02D21F84ACFAB738BBE45DA885CECCCF9FBC956861B0694397A1EC01EA290&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

> [投票系统工作量评估.pdf](https://github.com/JCCDex/ProjectFundingProposal/files/3591976/default.pdf)
> 提交方案详细设计和工作量文档，不做匿名投票，因为发交易形式无法匿名。投票结束以区块号形式结束，这个是变相时间为限制，投票人数无法限制，因为投票需要一个确认时间，很容易多投票

108个工数

**Comment by ApisChen** [comment]
> [支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=64B02D21F84ACFAB738BBE45DA885CECCCF9FBC956861B0694397A1EC01EA290&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
> 
> > [投票系统工作量评估.pdf](https://github.com/JCCDex/ProjectFundingProposal/files/3591976/default.pdf)
> > 提交方案详细设计和工作量文档，不做匿名投票，因为发交易形式无法匿名。投票结束以区块号形式结束，这个是变相时间为限制，投票人数无法限制，因为投票需要一个确认时间，很容易多投票
> 
> 108个工数

投票人数、时间都可以通过中心化服务器限制

**Comment by ApisChen** [comment]
目前进度约70%，正在做TP钱包对接工作。

**Comment by ApisChen** [comment]
已开完完成，基于tp钱包开发，请公测验收。http://47.92.110.121/voteApp/

**Comment by liufei7524** [comment]
投票显示操作成功后，却还要继续输密码，输了两次后还是如此，而且投票也没成功。

**Comment by liufei7524** [comment]
随便乱输的建立投票内容，不输密码，退回来，却能在后台看到这些无效的投票选项。

**Comment by ApisChen** [comment]
> 随便乱输的建立投票内容，不输密码，退回来，却能在后台看到这些无效的投票选项。

这些投票是本人创建的，在H5和后台管理都可以删除。

**Comment by ApisChen** [comment]
> 投票显示操作成功后，却还要继续输密码，输了两次后还是如此，而且投票也没成功。

这个问题怎么都没复现，协助我们一起调试下。

**Comment by zhinan** [comment]
@ApisChen 请在这个issue里发布bug和回复，谢谢！ @wenbo1039，@dragonfly2017，@tigerblock

**Comment by liufei7524** [comment]
后台中，浏览器是后退键没用，点了后页面一直没反应，不会返回。点多几次还会让让页面卡死，只能关了重开

**Comment by ApisChen** [comment]
> 后台中，浏览器是后退键没用，点了后页面一直没反应，不会返回。点多几次还会让让页面卡死，只能关了重开

不要点后退，点菜单键，另使用chrome浏览器兼容性最好，360的话选用极速模式。

**Comment by ApisChen** [comment]
测试完成，准备交付。

**Comment by ApisChen** [comment]
https://github.com/gaoshan-tech/moacVote
源码地址

**Comment by ApisChen** [comment]
https://github.com/gaoshan-tech/moacVote
源码地址
