### ISSUE TITLE
PFP23 MOAC应用链一键发链的商务演示DEMO

### ISSUE THREAD

**Issue by gwang74** [JCCDex/ProjectFundingProposal#24]
鉴于之前关于一键发链的相关意见，即利于应用链的商务推广，提出此次提案。演示DEMO分为服务端和WEB端。

- 服务端：nodejs,docker

 1. 应用链一键发链，基于[PFP03 墨客一键发链](https://github.com/JCCDex/ProjectFundingProposal/issues/3)，默认VNODE和SCS节点（由基金会决定）；提供用户自由设置节点的接口；默认发链的主账户（由基金会决定）；默认相关参数，如保证金，应用链数；

 3. 演示生成的应用链定期清除，拟采用数据库记录应用链地址，定期执行应用链关闭方法；也提供页面手动关闭的选项；

- WEB端：VUE

 1. 应用链发链网页，基于[PFP03 墨客一键发链](https://github.com/JCCDex/ProjectFundingProposal/issues/3)，对于页面涉及到的名词做到明确化的注释；

- 工作量

1. 整体服务框架的搭建及Docker镜像  2/人日

2. 应用链一键发链，在之前一键发链的基础上对相关功能的方法做接口封装及发链页面接口替换 15/人日

3. 应用链的定期清理 4/人日

4. 应用链发链完成后的展示，跳转[墨客浏览器](http://explorer.moac.io)子链合约地址的查询结果页面；（暂有待验证）

总计：21/人日

**Comment by lospringliu** [comment]
2. 定期关闭， 建议不要使用数据库， 应该直接记录到链上， 墨客链最好， 井通链也可以。记录地址固定

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=529928F96C653767819EF01158234E71CE22FFC8E0BAE5C7EE0056F4CD3FE9F7&wallet=j4vvoL3qU5NbWhrBzGJUejN6ADaz6SZ1me)

**Comment by lospringliu** [comment]
@gwang74 , 报一下进展百分率

**Comment by gwang74** [comment]
@lospringliu  @AnFengDe  @Yelvabaoji 项目已完成交接。
项目地址：https://github.com/HFJingchuang/MOAC_BUSY_DEMO

**Comment by gwang74** [comment]
进度：100%

**Comment by Feng1023** [comment]
可以把BLS的完善一下吗
