### ISSUE TITLE
PFP24 支持井通、墨客的baas平台

### ISSUE THREAD

**Issue by abc114437** [JCCDex/ProjectFundingProposal#25]
为方便用户接入区块链，降低使用区块链门槛，现开发baas平台。
需求：[https://shimo.im/docs/YrDQKtghWvgVt8PG](https://shimo.im/docs/YrDQKtghWvgVt8PG)
开发计划：[https://shimo.im/sheets/tdpxYc6ypWcQhwYy](https://shimo.im/sheets/tdpxYc6ypWcQhwYy)

**Comment by xmzhou2019** [comment]
看工数预测，有些测试和撰写文档的都没有计算啊。

**Comment by abellq** [comment]
开发计划里面貌似少了：实名认证、删除账户等

**Comment by AnFengDe** [comment]
EOS,以太好像不在我们资助范围。。。。
其次是测试（用例），文档这些工作
建议按照项目进度支付，并需要在社区寻找独立第三方进行评审

**Comment by lospringliu** [comment]
和中阳聊过，先消化下

**Comment by lospringliu** [comment]
#### @abc114437 ， BAAS是一个比较大的项目， 按照委员会的意见，我们有如下要求：
1.  按进度阶段验收/支付， 比如每10%为一个阶段
2. 原则上只支持井通/墨客相关部分
3. 我们在社区招募一位审计，协调 文档/进度/验收

**Comment by lospringliu** [comment]
鉴于目前重点是先做出一个产品，每个阶段的验收需要提供相应的文档

**Comment by abc114437** [comment]
@lospringliu 嗯  文档是并行做的

**Comment by abellq** [comment]
文档、进度等的验收标准是什么呢？

**Comment by lospringliu** [comment]
@abellq , 要求基本上照着文档能够搭出环境来，除了个别特殊的地方， 比如短信发送等

**Comment by abellq** [comment]
好的，那我申请审计可以吗？

**Comment by lospringliu** [comment]
可以，我给你登记

**Comment by abellq** [comment]
好的，期待！

**Comment by AnFengDe** [comment]
合计121个工数
[第一次支付30个工数](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=CFF26D159D2306B28D7C23B0298582FF7A6DCFBF0F49F7AA07A28D4C1678EE3A&wallet=j4yFbthaxy1vaSjXajz1eufJ5TtH2Vu3fF)

**Comment by abc114437** [comment]
https://github.com/abc114437/baas/tree/dev

**Comment by abellq** [comment]
源码下载不了，打开是：No results matched your search.

**Comment by lospringliu** [comment]
@abellq , https://github.com/abc114437/baas

**Comment by abellq** [comment]
只有一个README呀

**Comment by abellq** [comment]
VNODE数量 	SCS数量 	VNODE-SCS连接配置
  1 	                     3 	      1V-3S

版本：nuwa1.0.10

VNODE   192.168.0.11    系统：windows 10 64位

SCS1    192.168.1.10    系统：windows 7 32位
SCS2    192.168.1.88    系统：windows 10 64位
SCS3    192.168.1.66    系统：windows 7 64位

Monitor 192.168.1.11    系统：windows 10 64位

注意：
1. windows 2003 server SCS和VNODE无法互联。
2. 所有系统统一时间。

BAAS系统：总体上来说体验非常好，真正做到了程序化，智能化，大大缩减了部署基础链和应用链的难度和速度，使得开发人员能够专注开发自己的业务合约。
以下是在实际部署和测试过程中的一些细节提点建议！

1.实名认证：建议对idCard进行初步验证（身份证的格式验证）
2.认证钱包：建议对idCard进行初步验证（身份证的格式验证）
3.钱包绑定邮箱：建议对idCard进行初步验证（email的格式验证）
4.修改支付密码：建议对新密码进行位数限制
5.重置支付密码：建议不要把支付密码存放在邮箱，可以发送一个显示密码的有时效性的网页到邮箱，然后打开网页可以查看到密码，过段时间网页自动失效。
6.应用接口->4.新增app墨客代币：sign提示修改一下：如 a=1&b=2&c=3&appSecret=666 修改成：a=1&appSecret=666&b=2&c=3
7.墨客子链接口->7.注册成为子链monitor。因为子链monitor比较关键，设置错误了，会导致后续无法进行。建议重新设置过一个新的monitor，系统就默认用新的monitor。
8.部署子链dappBase合约。这里的dappBase合约编译器版本必须和部署子链业务合约的编译器版本必须一致（如：都用0.4.24版本  勾选optimize进行编译），否则业务合约会注册不上。

最后感谢@abc114437等开发人员的帮助！

**Comment by Yelvabaoji** [comment]
我在梳理一遍所有的项目。请问这个现在按完成度来说，百分比是多少？更具体一点，墨客的百分比是多少？墨客子链的百分比是多少？

**Comment by Yelvabaoji** [comment]
嗯，当然还有井通的百分比。还有有没有预计完成的时间？

**Comment by abellq** [comment]
应该是都完成了吧！

**Comment by Yelvabaoji** [comment]
@abc114437 你好，能否回应一下啊？

**Comment by abc114437** [comment]
已经完成了，针对一次审计的结果已经修改，是否还需要二次审计？

**Comment by Yelvabaoji** [comment]
第一次有审计我觉得也可以了。那么问题是代码还没有提交。只有readme @abc114437

**Comment by abc114437** [comment]
在dev分支上

**Comment by abellq** [comment]
二次审计
1.实名认证：建议对idCard进行初步验证（身份证的格式验证） 
 已经加上身份证的格式验证！

2.认证钱包：建议对idCard进行初步验证（身份证的格式验证）
已经加上身份证的格式验证！

3.钱包绑定邮箱：建议对idCard进行初步验证（email的格式验证）
已经加上email的格式验证！

4.修改支付密码：建议对新密码进行位数限制  
已经加上！

5.重置支付密码：建议不要把支付密码存放在邮箱，可以发送一个显示密码的有时效性的网页到邮箱，然后打开网页可以查看到密码，过段时间网页自动失效。
已经加上：发送到邮箱的是10分钟有效的重置支付密码链接，用户可以自主修改。

6.应用接口->4.新增app墨客代币：sign提示修改一下：如 a=1&b=2&c=3&appSecret=666 修改成：a=1&appSecret=666&b=2&c=3
已经修改！

7.墨客子链接口->7.注册成为子链monitor。因为子链monitor比较关键，设置错误了，会导致后续无法进行。建议重新设置过一个新的monitor，系统就默认用新的monitor。
重新组了一个子链，加了3个子链monitor，3个monitor都可以运行正常。

**Comment by lospringliu** [comment]
@AnFengDe ， 看看如果支付完成可以关闭了

**Comment by lospringliu** [comment]
@abellq , 联系 @AnFengDe 支付， 如果还没有支付审计报酬

**Comment by AnFengDe** [comment]
# BAAS平台概述
BaasBlockchain as a Service，区块链即服务，它为区块链技术和应用提供了基础设施支撑，可以进行快速的区块链的运维部署，加快区块链应用开发的速度，并且通过成熟的云计算技术，来满足初创企业、中小企业、学术机构、开源机构等企事业单位对区块链应用的需求，完善区块链的生态服务推动区块链向更多领域拓展。
## 开发支持
* 标准化开发工具：API
* 行业应用工具
* 高性能云服务框架
## 平台接入
### 应用接入登记及初始化
登记编号、名称等应用信息，获取访问凭证、回调地址
可选支持区块链底层：：SWTC、MOAC、ETH、EOS等
创建或导入应用钱包、（部署合约）创建Token，合约支持ERC20、ERC721标准
创建用户钱包、同步用户余额、
### 墨客子链接入
墨客应用子链部署
母子链充提币
子链转账
子链业务合约部署及调用
### 账户操作
一个用户在同以底层对应同一个钱包地址，并对应多个应用账户（可选）
一个应用账户可创建或绑定多个钱包，并设置交易密码
在APP中账户注册、实名认证、删除账户、查询账户列表
转账、文本上链，获取交易信息，获取历史交易信息
获取钱包余额、账户余额
钱包绑定邮箱，绑定后可找回交易密码
修改支付密码、查询密码
导出钱包公钥、私钥
### 批量转账
### 公共服务：
自主转账（充值）、部署合约、文本上链、查询
## 部署合约
支持墨客、以太坊合约
部署合约
部署ERC20、ERC721合约
部署业务合约
合约调用
支持通用ERC20、ERC721方法调用
调用非交易类方法
调用交易类方法
