### ISSUE TITLE
PFP26 开发一个朴素的预言机

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#27]
Oraclize，是区块链上重要设施，用来采集外部数据上链

这玩意说起来也很复杂，我们先弄个简单的：定时任务

提供一个合约接口，可以调用客户的合约接口，启动回调执行定时任务

如果需要消耗MOAC,应该是客户合约支付

可能我们对gas消耗估计不准，先搞个跑起来吧

工数预算：
1、预言机合约：4天
2、文档：2天
3、充值和任务执行显示DAPP 5天

**Comment by Yelvabaoji** [comment]
没有明白什么东西，希望可以把文档写得全一点。

**Comment by lospringliu** [comment]
这个要求文档要详细些

**Comment by AnFengDe** [comment]
预言机本质是将链外信息写入链内的一个中心化的服务，当然通过多签方式可以变成一个半中心化半去中心化的服务。

落实到定时任务上，应该是两个部分组成
1. 注册定时任务的合约，由客户方合约注册什么时候需要发起调用，以及执行业务逻辑的callback函数
2. 链外运行的crontab任务，定时查询注册合约，需要发起调用时，则驱动合约调用

**Comment by AnFengDe** [comment]
[第一次支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=5717AD8731B1E2E067CF2A3B640AE4DD02EDEA2568107396D94286275A4AB9C7&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by zhinan** [comment]
请更新提案进度

**Comment by Yelvabaoji** [comment]
等待DAPP上架TP钱包。

**Comment by AnFengDe** [comment]
项目完整资料： https://github.com/JCCDex/jcc_moac_alarm

DAPP正在开发上架之中

**Comment by AnFengDe** [comment]
[DAPP链接](https://dapp.tokenpocket.pro/share/index.html?url=https://oracle.jccdex.cn/#/)，可以用TokenPocket钱包打开运行
