### ISSUE TITLE
PFP 37: 分层钱包/助记词对井通的支持库 （bip32/39/44）

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#29]
#### 需要 利用/包装 bip32 / bip39 / bip44 成井通能直接使用的库

- 参考 ripple / 以太坊 生成 熟悉从助记词 到 钱包的流程
- 更新 https://iancoleman.io/bip39 （ https://github.com/iancoleman/bip39） ， 添加 井通和墨客
  - 发布页面到 netlify.com
  - 提交PR给  https://github.com/iancoleman/bip39  
- ~~包装成库~~ 调整现有的开发库，以适应bip32操作
  - 要求 webpack / browserify 零配置支持
  - 助记词 -> 种子 -> 井通bip32主钱包 -> bip44派生钱包
  - 助记词 -> 熵 -> 密钥 -> 钱包
- 参考工时

| 组件           | 内容                                                                          | 参考工时           |
| ----------- | ----------------------------------------------- | ---------------- |
| 熟悉流程     |  了解比特/以太/瑞波                                               | 1 |
| 井通/墨客    |   生成井通墨客地址 和 分级钱包                                                | 2 |
| https://iancoleman.io/bip39   | 添加井通墨客支持， 发布netlify.com              |2|
| PR | github.com/iancoleman/bip39  | 2 |
| 更新库  | keypairs / wallet / transaction / nativescript | 2 |
| 文档 | https://swtcdoc.netlify.com/docs/wallet/ |  1 |

**Comment by VVanaheim** [comment]
现在主流交易所钱包是优盾那几个吧

**Comment by AnFengDe** [comment]
这个原理是啥，能解释下吗，搞个中文的助记词，是不是很好玩？

**Comment by lospringliu** [comment]
不管硬钱包，至少提到的那个网站上需要支持井通/墨客， 中文助记词其实挺方便

**Comment by hanwencheng** [comment]
不需要单独的库了，基于[bip39](https://github.com/bitcoinjs/bip39) 并对[jcc_jingtum_base_lib](https://github.com/JCCDex/jcc_jingtum_base_lib)做部分改动可以实现，
改动需要讲`jcc_jingtum_base_lib`里的encode和decode功能提取出来，在以下代码中我把他们变成了static函数。

代码如下：
```javascript
const KeyPairs = require('./keypairs');
const bip39 = require('bip39');

export const secretToMnemonic = secret => {
	const bufferEntropy = KeyPairs.decode(33, secret);
	const hexEntropy = base16.encode(bufferEntropy);
	return bip39.entropyToMnemonic(hexEntropy);
};

export const mnemonicToSecret = mnemonic => {
	const recoverHexString = bip39.mnemonicToEntropy(mnemonic);
	const recoverHexBuffer = base16.decode(recoverHexString);
	return KeyPairs.encode(33, recoverHexBuffer);
};
```

**Comment by lospringliu** [comment]
还是需要的， jcc_jingtum_bnabse_lib应该不再维护了

需要使用swtc-keypairs 或者 swtc-codecs 库
更新网站 / 包装兼容性 / nativescript支持的工作都需要花些精力

**Comment by GinMu** [comment]
jcc_jingtum_base_lib基本上不会维护了，相关更新可pr到swtclib @hanwencheng

**Comment by lospringliu** [comment]
这个我自己来做了

**Comment by lospringliu** [comment]
### 进度
10%  熟悉bip39 / bip32 /bip44
20% 文档
40% keypair/wallet 更新以启用直接基于私钥的操作  Keypairs.deriveKeypair() / new Wallet() / Wallet.fromSecret()

**Comment by lospringliu** [comment]
> 不需要单独的库了，基于[bip39](https://github.com/bitcoinjs/bip39) 并对[jcc_jingtum_base_lib](https://github.com/JCCDex/jcc_jingtum_base_lib)做部分改动可以实现，
> ```
> 
> 另外有一个需要注意的是随机生成的entropy转换为hex之后，有可能hexEntropy.length = 15，这个时候没有达到entropyToMnemonic最低16位的要求，会报错。需要重新生成。
> 
> 稍后钱包完成之后我会开源钱包的代码。

https://swtcdoc.netlify.com/docs/wallet/ 新文档 直观操作， 支持HDWallet

**Comment by yongjunfan0723** [comment]
###  PFP 37 审计
1. 审计版本: @swtc/wallet@1.0.11 @swtc/lib@1.0.7
2. 审计人: [yongjunfan0723](https://github.com/yongjunfan0723)
3. 审查方法: 代码review及可用性测试, 测试代码[bip-test](https://github.com/yongjunfan0723/bip-test)
4. 审计内容:
    审计bip32，bip44分层钱包，bip39助记词 对井通和墨客的支持
5. 审计结果:
   i . 已添加井通墨客支持，发布到 [网站](https://swtcbip39.netlify.com/)
   ii.  PR [#403](https://github.com/iancoleman/bip39/pull/403) 已merged
   iii. 相关scoped包已更新
   iv. 文档已更新

**Comment by yongjunfan0723** [comment]
钱包: jURJTtmfYWuSzGRxJHYxxw3ijd4DTpe3it

**Comment by AnFengDe** [comment]
[费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=53322DFF086C655D3FB4B332EF4A334D44088E92E4D6A9F12E7E4B2A658A0DCE&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[审计费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=D81096865FF46F3EEC9123E89A6D9705539777627B905F6C4E41CF84D7CD6BB4&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[审计费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=B5057EC45EDDE6B71C9E19B0D5198ECD63566DA1E5B559845A6373B35C50C339&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
