### ISSUE TITLE
PFP03 墨客子链一键发链

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#3]
墨客子链搭建有好几个步骤，这些步骤应该是可以编程的，实现一键发链的目的

这个可以用nodejs脚本，shell脚本开发，或者其他的能实现的均可

**Comment by Astomsh** [comment]
开发目标：实现墨客子链的一键安装，子链出块
费用预估：1个人月/10K

**Comment by leoomo** [comment]
有搭建的相关资料吗？

**Comment by wangyifan** [comment]
> 有搭建的相关资料吗？

可以参考墨客文档的[子链搭建部分](https://moacdocs-chn.readthedocs.io/zh_CN/latest/subchain/%E5%AD%90%E9%93%BE%E7%9A%84%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%95.html)

**Comment by Astomsh** [comment]
具体的计划如下，如有其他建议、需求或错误也欢迎提出！
墨客子链一键安装脚本开发清单：https://shimo.im/sheets/KR5FMGXUrU42Tfte/MODOC

**Comment by gwang74** [comment]
https://github.com/gwang74/moac_xpress

**Comment by gwang74** [comment]
在MOACCHAIN提供的脚本基础上，完成的墨客子一键链搭建脚本。

本脚本可完成的功能：

部署子链出块
添加新的子链
添加监听子链
关闭子链

其中部署子链出块主要是MOACCHAIN提供的脚本完成的，其他三个是我们新增添的功能。

https://github.com/gwang74/moac_xpress.git

**Comment by AnFengDe** [comment]
关于一键发链，和墨客团队沟通了一下，大概可以分为三个层面来看待

1. 官方脚本
无须多言，通过官方文档和预先提供的AST,ASM脚本，加上简单的输入，可以构建好子链
1. 自动构建脚本
问题在于SCS账本需要同步，也许需要两天，这个改进办法是从已有的SCS上导出账本，导入到新SCS节点上，同步时间将会缩短，用户能尽快建立起自己子链
1. 预建立
官方团队先注册好SCS，用户直接拿去用，相当于毛坯房自己精装修

**Comment by gwang74** [comment]
已完成，在Windows和Linux系统下均测试通过，成功部署子链。
版本库：https://github.com/gwang74/moac_xpress
望社区验收，不足之处会积极修正。

**Comment by lospringliu** [comment]
Mac下测试可以成功部署子链

在终端下的窗口中的输出很有价值，而在浏览器中只能被动等待，建议把终端输出同时显示在浏览器界面中的一个tab中

**Comment by gwang74** [comment]
刚开始写的时候就有这个想法，想着使用websocket实现的，可惜没有成功，后面会争取把这个实现的。

**Comment by lospringliu** [comment]
输出写入到vuex中就可以放到页面上了

**Comment by abellq** [comment]
Windows 7 下测试可以成功部署子链！
![一键发链](https://user-images.githubusercontent.com/46801281/63149855-e1784280-c037-11e9-89ad-315dd2cc94e3.png)

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=98B3949B5B7858B5A3F41882936585D1CF1E6C8EBDE629E67C9E40B81AD97DFD&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by foreso-GitHub** [comment]
Windows 10和Ubuntu 16.04 下测试可以成功部署子链！

**Comment by xxjr2010** [comment]
安装了一天终于成功部署子链了。我的系统是 Windows 10 64位。其中有点波折。
1.配置环境中成功了：Node.js V8.0  + VS2013
如果Node.js 大于8，则需要VS2017或者更高的版本。
2.在：C:\moac_xpress-master\node_modules\opn\index.js 的23行，出现：
 error: uncaughtException: Unexpected token ... 
修改index.js 第23行，将“...options” 修改成“options”，再运行就成功。

**Comment by xxjr2010** [comment]
![windows10](https://user-images.githubusercontent.com/54310618/63337834-3f789300-c374-11e9-8d51-c9d83920fefc.png)

**Comment by xxjr2010** [comment]
我的钱包：jBCt5EiQJUXbQQ3FDdkne9adw5bZh5K44K

**Comment by jyj545** [comment]
linux mint 下测试可以成功部署子链！
![63357968-e6712500-c39c-11e9-95e3-87c27aecc904](https://user-images.githubusercontent.com/3349336/63661068-c9e54a80-c7eb-11e9-8251-7cd48bc6fdf1.png)
我的钱包：jac1nNfVMMawUSqRiauvXm2jhPj1E4Gukk

**Comment by AnFengDe** [comment]
收集到的反馈来看，系统可用，但是也有一些新的需求建议
1、需要装nodejs啊，环境啥的，对非技术人员要求过高
2、商务售前需要向用户演示，不能发链就完事了，有个DAPP演示是否更利于商务进行推广
3、用户演示的子链能否在一定时间，比如7天后自动消失，因为售前商务会没事就演示，产生很多废链

个人看法：毕竟这个是针对码农考虑的，如果要求降低，那就应该考虑建立一个网站服务来处理，从安全角度来说，钱包密钥要么用moacMask来搞，要么将WEB页面变成本地打开，用RESTful方式请求网站服务方式

对于一个具体的业务来说，发链是一个低频操作，投入很大的精力去开发，其实对商务的意义更大一些，毕竟不同的业务，合约都是不同的，与开发一个业务合约的工作量相比，发链的人力和时间成本都可以忽略不计。

所以这应该是商务人这种不懂技术的，瞎几把提的需求。
