### ISSUE TITLE
PFP27 建立一个查询SWTC钱包风险提示的合约和DAPP

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#30]
目的：
近期SWTC钱包大批被冻结，并处理解冻中。从个人风险和业务风险来说，如果提供一个查询机制，反馈该钱包的风险，对个人和项目方都有好处，尽力避免再使用老钱包地址参与业务。

思考：
钱包地址本身有一定个人隐私性质，因此我们考虑将地址的hash值在外部计算后传入合约保存，查询者可以直接发送自己地址，合约计算hash并查验是否存在风险。

这样可以做到在公链上不会暴露钱包地址信息，又能进行风险查询。查询者无须费用。

工作内容：
合约：3天
访问接口说明：1天
DAPP前端：3天

**Comment by AnFengDe** [comment]
[第一次支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=5717AD8731B1E2E067CF2A3B640AE4DD02EDEA2568107396D94286275A4AB9C7&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by VVanaheim** [comment]
可以试试优盾钱包，安全性和使用感都挺好

**Comment by AnFengDe** [comment]
优盾钱包是个啥？去中心化的钱包肯定最安全，SWTC钱包可选的也挺多
