### ISSUE TITLE
PFP 103: 寻求底层产品自动化测试人员

### ISSUE THREAD

**Issue by caivega** [JCCDex/ProjectFundingProposal#31]
兼职，付币

主要工作是对链及ipfs产品等底层产品进行自动化测试，
具体的包括如下三点内容：
1. 编写测试计划
2. 根据测试点写自动化测试脚本
3. 生成并编写测试报告

可长期合作

**Comment by AnFengDe** [comment]
工作内容太泛了，明确下，好估计工作量
--------------
如果是找合作方，长期合作，请给出美好前景

**Comment by lospringliu** [comment]
我猜缺的是CI， 自动化没有做好。 测试还是应该边开发边测试

**Comment by Yelvabaoji** [comment]
找到人了，关闭。
