### ISSUE TITLE
PFP01 swtclib维护更新

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#32]
五月份完成 swtc-lib 后， 基本上每个月都要花一两天更新。 其实还是有很多可以提高的地方，比如发布esm格式库， 测试永远有改进空间

日常是需要在功能上赶上官方jingtum-lib的脚步， 主要是 收费挂单和多方签名； 另外也接收了社区的贡献包括井畅的serialier的typescript化， Weijia的ipfs相关的更改 以及A计划（未批准）相关的实现

目前出来一个比较大的变动，多方签名， 需要静下来花些精力了。除了支持多签，这次会顺带把serializer中不一致的常量和官方统一。

[工作量预估](https://github.com/swtcca/roadmap/blob/master/workloads/updates.md)

**Comment by lospringliu** [comment]
文档： https://swtcdoc.netlify.com/docs/swtclib/#multiSign
源码： https://github.com/swtcca/swtclib/commit/4c8251e411912a6e5f97db47e25995730d28d033

90%

**Comment by GinMu** [comment]
# swtc-transaction多签名审计

1.  版本: 1.2.26
2. 审计人: [GinMu](https://github.com/GinMu)
3. 审查方法: 代码review和在测试链上实际测试, 测试代码[swtclib-test](https://github.com/GinMu/swtclib-test)
4. 审计内容:
    1. 设置多签列表，查询多签列表信息和提交多签交易
5. 审计结果:
    1. 在测试链上设置多签列表，查询多签列表信息和提交多签交易成功
    2. 单元测试已覆盖
    3. 文档已更新
6. 建议:
    1. [ISignerListTxOptions](https://github.com/swtcca/swtclib/blob/master/packages/swtc-transaction/tssrc/types.ts#L137) `lists`最好不要定义成`any[]`, 可选参数`address`并未实际使用
    2. 针对多签数据组装和验签可以抽取出来，作为单独的工具库，方便第三方直接调用
    3. [fee](https://github.com/swtcca/swtclib/blob/d738e2db3fbd747c43ef9fb988258efb25dd36fa/packages/swtc-transaction/tssrc/transaction.ts#L1281)校验存疑，实际测试来看，fee设置为10同样可以提交成功
7. 结果: 通过

**Comment by Xiaohao204** [comment]
# swtc-transaction多重签名审计

1. 版本: 1.2.26
2. 审计人: [xiaohao](https://github.com/Xiaohao204)
3. 审查方法: 代码review和在正式链上实际测试, 测试代码[swtclib-test](https://github.com/Xiaohao204/swtclib-multisign-test)
4. 审计内容:
    1. 设置多签列表，查询多签列表信息，提交多签交易，废弃主账号密钥和激活主账户密钥
5. 审计结果:
    1. 在测试链上设置多签列表，查询多签列表信息，提交多签交易成功，废弃主账号密钥和激活主账户密钥
    2. 单元测试已覆盖
    3. 文档已更新
6. 建议:
    针对多签数据组装和验签可以抽取出来，作为单独的工具库，方便第三方直接调用
7. 结果: 通过

**Comment by lospringliu** [comment]
@GinMu , 费用最终取决于区块链底层
合约因为只有ts5环境，好像现在跑不通， 不过不值得立刻去排查，等成熟后再讲

**Comment by zhaitianye** [comment]
# swtc-transaction多重签名审计
1. 版本: 1.2.26
2. 审计人: [翟天野](https://github.com/zhaitianye)
3. 审查方法: 代码review和在正式链上实际测试, 测试代码[test_swtc_lib_proxy](https://github.com/zhaitianye/test_swtc_lib_proxy/tree/master/src/t-swtc-lib/Multiple-signature)
4. 审计内容:
   1. 设置多签列表
   2. 查询多签列表信息
   3. 提交多签交易方式1
   4. 提交多签交易方式2
   5. 废弃主账号密钥
   6. 激活主账户密钥
5. 审计结果:
   1. 在正式链上设置多签列表
   2. 查询多签列表信息
   3. 提交多签交易成功
   4. 废弃主账号密钥
   5. 激活主账户密钥
   6. 单元测试已覆盖
   7. 文档已更新
6. 建议:
   1. 设置帐号的签名列表，buildSignerListTx在传入参数时候，是否应该和rpc上的一致，使用 SignerQuorum和SignerEntries变量命名，降低开发者疑惑
   2. 需要设置足够的燃料支持多签交易，这个燃料什么时候会用到，需要用多少，最低和建议设置多少，具体场景应做详细说明
   3. 激活主密钥的时候需要完整的列表还是只需要账号阈值大于设置的阈值即可，需要在文档里面做出说明
   4. 是否有一个接口来查询废除主秘钥之后的状态。
   5. 设置账号的多签列表之后，此账号为多签账号，可否有方法把此账号设置回来，即设置为普通账号
   7. 批量签名的签名列表是2-8个，这个是否应该在文档里面进行说明，超过8个会提示失败
7. 结果: 通过

**Comment by Xiaohao204** [comment]
j3zEdnLUMQ6rXsKk8zNCotdNNfh4avFttK

**Comment by zhaitianye** [comment]
jEd4Vmp9Hr3d6snwcSsBy6Gt25kzkHLQWt

**Comment by GinMu** [comment]
jwnqKpXJYJPeAnUdVUv3LfbxiJh5ZVXh79

**Comment by AnFengDe** [comment]
[付费记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=557DD132A00938C860232EB264EDFDF54FBD131A4AE6CD8C2E8A3B19FA3A7153&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
审计评估是3个工作日，有3人提交，为鼓励大家，发三份审计费用
[@Xiaohao204 付费记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=6258A169860B9E4384BDD198A0A27C6E7D10BDC18FF7B65ECF7C3C1D3E4ABF03&wallet=j3zEdnLUMQ6rXsKk8zNCotdNNfh4avFttK)
[@zhaitianye 付费记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=6981869D404F28304826A5215E0517A74A5B8F9DABEE01DDC785F8C7BE4C5B21&wallet=jEd4Vmp9Hr3d6snwcSsBy6Gt25kzkHLQWt)
[@GinMu 付费记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=87BE3B3804B5AED69E9CE1A12F14FCE08ED62E1341D9CF901A4618C1BE15A8D7&wallet=jwnqKpXJYJPeAnUdVUv3LfbxiJh5ZVXh79)
