### ISSUE TITLE
PFP 27 基于PFP05 SWTC钱包开发DAPP store

### ISSUE THREAD

**Issue by gwang74** [JCCDex/ProjectFundingProposal#35]
目前PFP05 SWTC钱包开发第一阶段钱包基础功能的开发，Android版本已完成，iOS版也即将完成。所以提出第二阶段DAPP Store开发申请，为后续SWTC DAPP提供应用环境，构筑良好井通生态。

<table>
<tr>
    <td rowspan="7"> 完成状态：<br/>
        [√] Andorid<br/>
        [  ] iOS<br/>
    <td>开发项</td>
    <td> 工数</td>
</tr>
<tr>
    <td>js-sdk</td>
    <td>5</td>
</tr>
<tr>
    <td >JS调用原生接口类 JsBridge<br/>Android和iOS</td>
    <td>5</td>
</tr>
<tr>
    <td>Web疏通测试用例</td>
    <td>2</td>
</tr>
</table>

另需要审计一名，预计工数2人日。

总共数：14人日

**Comment by zhinan** [comment]
请更新提案进度

**Comment by gwang74** [comment]
已完成，项目地址：https://github.com/HFJingchuang/doughnut-js
另需要审计一名

**Comment by abellq** [comment]
测试设备：

模拟器
Google Nexus 4-4.4.4   Android 4.4 - API19
Google Nexus5 Android 6.0 - API23
Xiaomi Redmi Note 7 Android 9.0 - API28

真机
Honor 6X Android 8.0.0

测试结果：
除了 “donut.shareToSNS” 这个功能没有看到效果，其他的都可以！

**Comment by Yelvabaoji** [comment]
@gwang74

**Comment by Yelvabaoji** [comment]
结果你能说明一下吗？

**Comment by AnFengDe** [comment]
[开发支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=BE6F9BA207B36EE21895209044615CAA4539040E0AECFAF6A9050FFF6FE54821&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

[审计费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=BF79F57016675CA2919C43DF1ECC107842C588F8722AF0F97EFCA2D6182242B1&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
