### ISSUE TITLE
PFP 29 基于区块链的商城APP

### ISSUE THREAD

**Issue by baibingB** [JCCDex/ProjectFundingProposal#36]
到目前为止我们的区块链底层开发已经能够满足绝大多数的需求，基于现在的底层技术怎样在应用层上能够有更多元化的满足用户的使用，拓展区块链的用户群里，更深度的拥抱非技术人员，因此提出开发基于区块链的商城APP
1、开发完成后共享代码，其他人员不需要开发，只需要配置一下就能够将区块链的币作为结算依据
2、一个币种可配置一个商城，在商城中添加商品，便于区块链更深度的为普通人使用
3、商品包含购买功能、钱包兑换功能、钱包查看、下单、查看进度等，并提供相应的后台程序进行管控

详细功能清单及工作量请见：
《区块链商城APP功能清单》
https://shimo.im/sheets/wJ9CjJjCjTCDQcTP/MODOC/ 
--------------------------------------------------------------------------------------------------------
**感谢井通对我们的支持，目前1.0版本已研发完成
2019-09至2019-11历时2个半月时间，从PG发行开始研发
分享代码地址如下：
https://github.com/baibingB/SWTC_PGShop.git
链接: https://pan.baidu.com/s/17TG0JMZM_AC2cxHo0segvQ
提取码: 8gut**
---------------------------------------------------------------------------------------------------------
项目中包含接口程序和APP程序
接口程序对应接口文件加，其他为APP程序
接口程序，运行环境.NET Framework4.0，将接口程序包含即可
APP使用uniapp开发，包含项目中即可使用
-------------------------------------------------------------------------------------------------------
可直接在开发环境中运行
-------------------------------------------------------------------------------------------------------
APP商城main参数定义：
-用户搭建环境使用的接口地址
Vue.prototype.webUrlUser ='';
-井通服务器地址
Vue.prototype.webUrlSys ='';
-井通服务器信息地址
Vue.prototype.webUrlSysInf ='';
-商城运行账户
Vue.prototype.sysUser ='';
-兑换账户地址
Vue.prototype.sysUserChange ='';
-兑换账簿私钥
Vue.prototype.sysUserChangePwd ='';

**Comment by xing136xing** [comment]
希望得到区块链的支持，程序正在开发中

**Comment by yoyo09104758** [comment]
加油

**Comment by penlylu** [comment]
这个项目与区块链的结合点在哪里？是基于区块链实现的类似ecshop那样的电商通用后台吗？

**Comment by xing136xing** [comment]
是的，类似于ecshop，区别点在于结算可以使用区块链的货币结算，并且支持出示钱包二维码结算，以及后续可以扩展为图片的区块链存储，目前最大的亮点在于配置一下就可使用，可以制定币种结算，并且支持在APP种进行区块链的币种兑换，更大的推动区块链在普通用户中的使用

**Comment by yoyo09104758** [comment]
&nbsp;区块链： 记账，结算，通证。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"YGG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 下午3:24
收件人:&nbsp;"JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com&gt;;
抄送:&nbsp;"黑夜死神"<651868624@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [JCCDex/ProjectFundingProposal] 基于区块链的商城APP (#36)




这个项目与区块链的结合点在哪里？是基于区块链实现的类似ecshop那样的电商通用后台吗？

**Comment by zhinan** [comment]
这个App是你们正在运营的项目吗？我们更希望的是，开发方同时也在使用并运营该项目，这样有利于持续维护该项目。

**Comment by zhinan** [comment]
> 这个App是你们正在运营的项目吗？我们更希望的是，开发方同时也在使用并运营该项目，这样有利于持续维护该项目。
经过和开发者沟通了解到，该App是基于Moac链的 “PG”项目，同时在运营该项目。

**Comment by xing136xing** [comment]
是的，这个是我们正在运营的项目，还会持续优化

**Comment by zhinan** [comment]
代码请开源到github上

**Comment by xing136xing** [comment]
已分享

**Comment by zhinan** [comment]
请完善项目说明，如：使用及部署方法、配置文件说明、开发环境说明等。

**Comment by xing136xing** [comment]
项目中包含接口程序和APP程序
接口程序对应接口文件加，其他为APP程序
--------------------------------------------------------------------------------------------------------
接口程序，运行环境.NET Framework4.0，新建一个项目将接口程序包含即可
APP使用uniapp开发，包含项目中即可使用
--------------------------------------------------------------------------------------------------------
APP商城main参数定义：
-用户搭建环境使用的接口地址
Vue.prototype.webUrlUser ='';
-井通服务器地址
Vue.prototype.webUrlSys ='';
-井通服务器信息地址
Vue.prototype.webUrlSysInf ='';
-商城运行账户
Vue.prototype.sysUser ='';
-兑换账户地址
Vue.prototype.sysUserChange ='';
-兑换账簿私钥
Vue.prototype.sysUserChangePwd ='';

**Comment by silentvolcano** [comment]
请问这个项目后台代码开源了吗？目前似乎只看到了前端代码？

**Comment by xing136xing** [comment]
GIT中将接口的代码放在接口文件夹下，百度云盘中将两份代码放在不同的压缩包中

**Comment by xing136xing136** [comment]
BUG：维护地址时出现undefined，导致生成订单后，订单信息无法查询

**Comment by xing136xing136** [comment]
BUG：自动更新程序点击确定后无法更新

**Comment by xing136xing136** [comment]
优化：第二个页面评论页面头部遮挡顶部状态栏，需向下10像素

**Comment by xing136xing136** [comment]
BUG：PG币替换为其他币种时，结算币种应显示为其他币种

**Comment by xing136xing** [comment]
已修改，请测试

**Comment by xing136xing136** [comment]
测试完成，BUG已验证无问题，测试报告如下

[PG-代码审计及测试报告.docx](https://github.com/JCCDex/ProjectFundingProposal/files/3934811/PG-.docx)

**Comment by AnFengDe** [comment]
[支付记录，付清](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=295E5EEC1D0B1FBFA58907972F1E7463D4864DD1659A205589C252137864E46B&wallet=jntxe3fuW1J18h14yXpmoPZADkVSPEt3JZ)

**Comment by abellq** [comment]
后端的用户名和密码是什么呢？

**Comment by abellq** [comment]
C#,我不是很了解！但是呢，下面来自项目的Web.config中：
<connectionStrings>
    <add name="OracleConnString" connectionString="Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=)(PORT=))(CONNECT_DATA=(SERVICE_NAME=orcl)));Persist Security Info=True;User ID=;Password=;" providerName="Oracle.ManagedDataAccess.Client"/>
  </connectionStrings>
貌似未指定数据库连接的HOST，请求解答一下！

**Comment by abellq** [comment]
C#,我不是很了解！但是呢，下面来自项目的Web.config中：
`<connectionStrings>
<add name="OracleConnString" connectionString="Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=)(PORT=))(CONNECT_DATA=(SERVICE_NAME=orcl)));Persist Security Info=True;User ID=;Password=;" providerName="Oracle.ManagedDataAccess.Client"/
</connectionStrings>`
貌似未指定数据库连接的HOST，请求解答一下！
