### ISSUE TITLE
后台不支持批量删除投票

### ISSUE THREAD

**Issue by wenbo1039** [JCCDex/ProjectFundingProposal#40]
可能场景：比如一个人违规发了很多条奇奇怪怪的投票，我通过筛选选出他了。。然后想删他的多个投票的时候，只能一个个的删么？

希望支持：选中，选中多个，全选，反选然后批量删除功能

**Comment by JCCDex** [comment]
#23

**Comment by ApisChen** [comment]
> 可能场景：比如一个人违规发了很多条奇奇怪怪的投票，我通过筛选选出他了。。然后想删他的多个投票的时候，只能一个个的删么？
> 
> 希望支持：选中，选中多个，全选，反选然后批量删除功能

批量删除很危险，系统设计不是每个人都能发起投票，只有授权的才可以。
