### ISSUE TITLE
后台头像加载慢

### ISSUE THREAD

**Issue by wenbo1039** [JCCDex/ProjectFundingProposal#42]
1.后台头像（如果有头像）加载特别慢，就几个小图加载了好几秒。
2.如果没有上传头像，则显示加载失败，这里可以直接显示无，而不是加载失败。

**Comment by JCCDex** [comment]
#23

**Comment by ApisChen** [comment]
> 1.后台头像（如果有头像）加载特别慢，就几个小图加载了好几秒。
图片没做CDN，目前H5、后台服务均对图片做了压缩处理，提交加载速度
