### ISSUE TITLE
前端创建投票时，图片应当是一种标的

### ISSUE THREAD

**Issue by dragonfly2017** [JCCDex/ProjectFundingProposal#43]
前端在创建投票时，图片应当成为一种标的，比如说我有三个图片方案要选。

而不是添加一张图片。

**Comment by JCCDex** [comment]
#23

**Comment by ApisChen** [comment]
为了节约服务器带宽，目前设计只能上传一张图片，可以把三个方案图片整合成一张去上传，然后选项还是留下a、b、c
