### ISSUE TITLE
白名单，黑名单的txt文件格式没有说明

### ISSUE THREAD

**Issue by dragonfly2017** [JCCDex/ProjectFundingProposal#44]
在后台投票列表里面，如果要加白名单，黑名单时，没有文件格式说明，根本没法加。

**Comment by JCCDex** [comment]
#23

**Comment by ApisChen** [comment]
黑白名单规则：
1. 如果没有设置黑、白名单，那么投票所有人都可见可投票
2. 如果单独设置了白名单，那么只有白名单里面人可见可投票
3. 如果单独设置了黑名单，那么只有黑面单里面的人不可见
4. 如果同时设置了黑、白名单，那么只有白名单里面排除黑名单剩下的人，可见可投票

**Comment by ApisChen** [comment]
[list.txt](https://github.com/JCCDex/ProjectFundingProposal/files/3844285/list.txt)

**Comment by ApisChen** [comment]
list.txt 是txt格式样本
