### ISSUE TITLE
MOMO测试投票3

### ISSUE THREAD

**Issue by tigerblock** [JCCDex/ProjectFundingProposal#45]
可以多选，多选的话，应该默认使用方框而不是圆弧。投票成功后，提示刷新成功，仍然显示0票，大约过了1分钟后，主动刷新，才看到投票数。

**Comment by tigerblock** [comment]
退出TP，重新进入投票系统，原来投票的记录不见了，可以继续投票？

**Comment by tigerblock** [comment]
继续投票，但是只是选择MOAC, 系统允许投票，投票成功后，看到投票详情里面有2个tiger。

**Comment by JCCDex** [comment]
#23

**Comment by ApisChen** [comment]
> 可以多选，多选的话，应该默认使用方框而不是圆弧。投票成功后，提示刷新成功，仍然显示0票，大约过了1分钟后，主动刷新，才看到投票数。

1. 我觉得方框和圆弧这个无所谓的，QQ群投票也都是圆弧，用户用习惯了就懂了
2. 投完票需要等区块确认的，这个有延迟是合理的

**Comment by ApisChen** [comment]
> 退出TP，重新进入投票系统，原来投票的记录不见了，可以继续投票？

没有发起交易的投票是可以继续投的

**Comment by ApisChen** [comment]
> 继续投票，但是只是选择MOAC, 系统允许投票，投票成功后，看到投票详情里面有2个tiger。

这个bug应该改掉了，发起一个新的投票项目进行测试看看
