### ISSUE TITLE
测试发布投票 tiger测试投票2

### ISSUE THREAD

**Issue by tigerblock** [JCCDex/ProjectFundingProposal#46]
添加管理权限后，在TP发起投票，点击发布没有任何提示信息。但是在投票管理系统已经看到19个投票项。投票详情里面只是显示了第一个选项。其实它是一个四选二， 猫， 狗（以及狗的表情图片），鸡（以及鸡的表情图片），兔子

**Comment by GinMu** [comment]
#23

**Comment by ApisChen** [comment]
> 添加管理权限后，在TP发起投票，点击发布没有任何提示信息。但是在投票管理系统已经看到19个投票项。投票详情里面只是显示了第一个选项。其实它是一个四选二， 猫， 狗（以及狗的表情图片），鸡（以及鸡的表情图片），兔子

这个数据好像删掉了，不太明白问题点在哪里
