### ISSUE TITLE
PFP31 移植ENS核心部分服务到墨客链上

### ISSUE THREAD

**Issue by AnFengDe** [JCCDex/ProjectFundingProposal#50]
# 需求
Name Service是业务系统需要的服务，显然转账给 jccdex.mc比一串地址好记的多。此外智能合约的注册发布的统一监听接口地址，也需要。

# 工作思考
ENS是以太社区的标准[EIP 137](https://eips.ethereum.org/EIPS/eip-137)所规定的的，配套的相关标准还有一大堆，开源代码也有，还有一个团队提供域名的竞拍服务。

作为解析器，可以解析地址，名称，反向解析，abi， 内容hash指纹，接口，公钥，文本。这是以太坊已经实现的功能。

* [ENS project](https://github.com/ensdomains/ens)
* [ENS Resolver project](https://github.com/ensdomains/resolvers)

更不要说还有配套的开发包，人机交互DAPP，APP。

井畅从自己角度出发，我们做不了这么多工作，核心的名称地址解析和注册，是需要的，其他的等业务成熟再说

该服务建立起来后，可以免费给社区钱包，各种应用使用。

# 技术工作的一些限制

* 需要通读代码，进行核心功能的剥离
* 代码降级，用0.4.24版本的solidity编译器，因为墨客最高就支持到这里了
* 数据备份问题，未来升级需要重新导入这些数据和他们的关系
* ENS默认基于.eth后缀展开，我们要基于.mc展开，有些内置数据需要重新运算

# 开发工数

* 移植注册核心代码并完善测试   10人天
* 移植解析合约核心代码并完善测试 10人天
* DAPP开发，功能包括：注册，更新和吊销  5人天
* 提供访问ENS的js开发代码      5人天

**Comment by AnFengDe** [comment]
[ens版本库](https://github.com/JCCDex/ens)

**Comment by lospringliu** [comment]
@AnFengDe , 这个如果已经在跑了的话就不需要进一步测试了， 可支付关掉

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=7AB40A92E9D207FF828E657CF6778F837956BDF7D274E53C2EED7CFBC0D09434&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
