### ISSUE TITLE
PFP32 墨客应用链浏览器开发

### ISSUE THREAD

**Issue by gwang74** [JCCDex/ProjectFundingProposal#51]
开发墨客应用链浏览器，便于查询应用链相关信息，包括通用类、充提类、交易类和业务类信息。
基于[墨客Client Nuwa v1.0.11](https://github.com/MOACChain/moac-core#nuwa-v1011)

<table>
<tr>
    <td colspan="3" align="center">开发目标<br/>
    <td rowspan="2" align="center">工作量预估(天)</td>
</tr>
<tr>
    <td align="center">功能模块<br/>
    <td align="center">详细功能</td>
    <td align="center">备注</td>
</tr>
<tr>
    <td align="left">信息展示</td>
    <td align="left">应用链基本信息展示</td>
    <td align="left">应用链相地址、owner、区块高度以及收益相关信息</td>
    <td align="right">10</td>
</tr>
<tr>
    <td rowspan="2" align="left">信息查询</td>
    <td align="left">地址查询</td>
    <td align="left" rowspan="2">支持查询充提类、交易类和业务类信息<br/>
        支持AST和ASM两种应用链<br/>
        支持条件过滤显示，例如日期过滤显示<br/>
        使用Mongo DB存储数据<br/>
    <td align="right" rowspan="2">50</td>
</tr>
<tr>
    <td align="left">哈希查询</td>
</tr>
<tr>
    <td colspan="3" align="center">开发小记（人/天）</td>
    <td align="right">60</td>
</tr>
<tr>
    <td colspan="3" align="center">审计</td>
    <td align="right">5</td>
</tr>
<tr>
    <td colspan="3" align="center">总计（人/天）</td>
    <td align="right">65</td>
</tr>
</table>

**Comment by lospringliu** [comment]
@gwang74 , 这个要把文档写清楚， 审计的一个要求是能按照文档搭出环境

**Comment by lospringliu** [comment]
子链是去中心化的， 相关信息如何获得？

**Comment by gwang74** [comment]
会写一个项目使用文档的，审计的过程如果有疑问也会做相应修改，保证项目的易用性。
子链的相关信息主要是通过monitor节点的rpc接口获取的。
@lospringliu

**Comment by gwang74** [comment]
已完成，项目地址：https://github.com/HFJingchuang/MOAC_AppChain_Explorer
测试查看地址：http://explorer.zcold.top
另需要审计一名

**Comment by abellq** [comment]
1. 建立一个测试网子链；
2. SCS监视器的启动参数必须是：rpc，不能rpcdebug；
3. 安装sails时候，附带需要安装 Microsoft Visual C++ ,并且版本要和Node想匹配。
4.. 在运行同步命令（sails run sync-micro-chain）或者 启动服务（npm run start）时候有可能会出现超时，多重复几次执行可以解决;
5. 安装运行 micro-chain-explore 相关命令，成功后，打开：http://localhost:8080可以看到MOAC应用链的浏览器了，在子链上转账，部署合约等都可以在浏览器查询得到;
6. 打开： http://localhost:1337 可以再加API的router可以得到相关数据；

经测试后一切正常运行。

**Comment by AnFengDe** [comment]
[开发费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=860DD2768ABC8039AF1EEA314900C1115E050F8A19261346F9E81B891E541184&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

[审计费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=603282B3D67B3E2DF12847E9744F519916FEE60D9D796B6AA885EF79FE759DAD&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
