### ISSUE TITLE
PFP34 菠菜游戏开发

### ISSUE THREAD

**Issue by jyj545** [JCCDex/ProjectFundingProposal#56]
社区可玩的菠菜游戏较少，因此开源我做的菠菜游戏，算是抛砖引玉。
游戏介绍：
１、前端vue后端nodejs+mongodb
2、基于井通公链，使用swtc-lib库
３、服务端自动优选稳定节点，长期使用不崩溃
４、玩法简单，支持自动下注，支持多种井通链上通证
-------------------------------------------------------------------------------------------
详细功能清单及工作量请见：
《菠菜小游戏(html5)功能清单》
https://shimo.im/sheets/v9tJhKrYQvKXhDJk/MODOC

**Comment by foreso-GitHub** [comment]
请提供功能文档和工作量估计。 @jyj545
