### ISSUE TITLE
PFP34 swtclib更新 - 全面支持ed25519

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#57]
### 要点
- 安全： 实现本地签名
- 透明： 最小化引入，不影响用户使用体验

- 工时 - 11

| 组件                | 内容                                                                      | 参考工时           |
| ------------- | -------------------------------------------- | ---------------- |
| 服务器签名   |                 尝试体验                                               | 1 |
| 参考文档       |   开发者文档 / jingtum-core                               | 2 |
| 参考库           |  keypairs binary-codec  cryptography             | 2 |
| 离线签名       |  尝试 单签 多签                                                   | 2 |
| 开发库更新   |  keyparis wallet transaction                               | 2 |
| 测试               |  单元测试例子                                                      | 1 |
| 文档               | 更新                                                                        | 1 |

**Comment by lospringliu** [comment]
进度：
10%   服务器签名 
50%  ripple资料，测试
70%  单签
80%  多签
90%  测试

文档：  https://swtcdoc.netlify.com/docs/swtclib/#ed25519
代码：  https://github.com/swtcca/swtclib/commits/master   一月十八号

**Comment by GinMu** [comment]
审计预估工时3个工作日

**Comment by GinMu** [comment]
# ed25519支持情况审计

1.  审计版本:   @swtc/lib@1.0.6
2. 审计人: [GinMu](https://github.com/GinMu)
3. 审查方法: 代码review和在链上实际测试, 测试代码[swtclib-test](https://github.com/GinMu/swtclib-test)下ed25519和secp256k1目录
4. 审计内容:
    1. 测试生成ed25519钱包和离线签名
5. 审计结果:
    1. 生成ed25519钱包成功
    2. 离线签名上链成功，并且是无感操作
    3. 单元测试已覆盖
    4. 文档已更新
6. 建议:
    1. 相关建议提交了一个[PR](https://github.com/swtcca/swtclib/pull/44).

**Comment by lospringliu** [comment]
多谢, 现在rollup对目前这样声明支持有点问题, 我看看如何merge

**Comment by GinMu** [comment]
> 多谢, 现在rollup对目前这样声明支持有点问题, 我看看如何merge

OK

**Comment by AnFengDe** [comment]
[开发支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=B6824B7EDE7ABB97142A9352C29CF768C14BFDBBD31347124E6A1C627A2662FA&wallet=j3vyFAMQW2Ls48eoFCTsMXFq2KNWVUskSx)

[审计费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=1B20760831C4D0564F9F7B091AFB18829BE5D3571228B0031F833EED0B5EFFB7&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
