### ISSUE TITLE
PFP35: swtc-lib 全面typescript化， 引入rollup构建系统支持ES模块， 增加scoped包发布

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#58]
### 要点
- 升级： x-address-codec不再维护， address-codec升级， 所有主版本升级
- 新特性： ESM支持
- 现代化： 新增scoped包发布 @swtc/wallet， @swtc/transaction ...

- 工时 - 12

| 组件                | 内容                                                                      | 参考工时           |
| ------------- | -------------------------------------------- | ---------------- |
| typescriptize |  address-codec, keypair                                    | 2 |
| typescriptize |  utils                                                                       | 2 |
| rollup打包      |  研究 rollup + plugins                                         | 2 |
| wallet以下包 ｜主版本 升级 修复单测  scoped发布              | 2 |
| 测试               |  单元测试                                                              | 2 |
| 文档               | 更新 为 scope                                                      | 2 |

**Comment by lospringliu** [comment]
文档： https://swtcdoc.netlify.com/
仓库：https://github.com/swtcca/swtclib

进度： 100%
内容：
1. 代码更新： 2020/01/26 - 2020/02/07
2. address-codec / keypairs / utils 全新升级并完全typescript化， chains更改为common， 作为零依赖内容的集中区
3. 所有包主版本升级，并且主流更改为scoped， 即 @swtc/common , ... @swtc/wallet, ... @swtc/lib..., 保持对前兼容，新发布的swtc-lib底层依赖已经全部更新为scoped包
4. serializer 和 utils彻底调整，和其它的包保持一致风格
5. 对于memo彻底实现，完全支持 json / hex 格式。 多签由于服务器方面错误处理，还需要跟井通协调
6. 文档全面更新

**Comment by GinMu** [comment]
审计预估工时7个工作日

**Comment by GinMu** [comment]
# PFP35审计

1.  审计版本:   @swtc/lib@1.0.6
2. 审计人: [GinMu](https://github.com/GinMu)
3. 审查方法: 代码review及可用性测试, 测试代码[swtclib-test](https://github.com/GinMu/swtclib-test)
4. 审计内容:
    1. 审计scoped包是否可用及es模块支持
5. 审计结果:
    1. 开源库[jcc_wallet](https://github.com/JCCDex/jcc_wallet)将原先依赖的老版本顺利迁移到新的scoped包版本，在node环境和浏览器环境下CI通过
    2. 单元测试已覆盖
    3. 文档已更新
6. 建议:
    1. 相关建议提交了一个[PR](https://github.com/swtcca/swtclib/pull/45).

**Comment by lospringliu** [comment]
PR 已 merge， 新版本发布

**Comment by GinMu** [comment]
> PR 已 merge， 新版本发布

OK

**Comment by GinMu** [comment]
jwnqKpXJYJPeAnUdVUv3LfbxiJh5ZVXh79

**Comment by AnFengDe** [comment]
[费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=97C899A45A38F24B775093156A8E020E8F43AE636C80636CE6BE0A798D924ED5&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[审计费用支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=E5758406C0AF2FAA4CFFB30F6744947534EC856D5CEA0FF221544F30E99FBFAB&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
