### ISSUE TITLE
PFP38: 增加基于RPC的井通开发库

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#60]
### 要点
- 安全第一， 全部只提供本地签名
- 尽量实现所有适用的jingtum-lib的功能
- ~包含所有jcc-rpc的功能~
- 完整的多签 / ed25519 以及proxy/api中合理的借用

- 工天 - 21

| 组件                | 内容                                                                      | 参考工时           |
| ------------- | -------------------------------------------- | ---------------- |
| 参考文档       |                 ripple + jingtum                                    | 3 |
| 参考文档       |                 jingtum-lib + jcc-rpc                           | 2 |
| 代码               |                 功能实现                                               | 7 |
| 文档               |   说明 / 参数 / 实例                                              | 7 |
| 测试               |   测试                                                                     | 2 |

**Comment by lospringliu** [comment]
新冠问题，得了拖延症，稍后开启

**Comment by zhinan** [comment]
@lospringliu ，请通告一下进度

**Comment by lospringliu** [comment]
10%

**Comment by lospringliu** [comment]
已完成， 请安排审计

代码： https://github.com/swtcca/swtclib/tree/master/packages/rpc

文档： https://swtcdoc.netlify.app/docs/swtcrpc/ 

测试： https://github.com/swtcca/swtclib/tree/master/packages/rpc/test

**Comment by lospringliu** [comment]
参考
[rpc接口整理.docx](https://github.com/JCCDex/ProjectFundingProposal/files/5742146/rpc.docx)

**Comment by abellq** [comment]
@lospringliu 你好！请问npm test 后出现：Error: Cannot find module 'C:\swtclib-master\packages\rpc\cjs\index.js'. Please
verify that the package.json has a valid "main" entry 。貌似源码里没有cjs这个目录，请问该怎么操作呢？请问你的QQ多少，我加你！

**Comment by abellq** [comment]
npm install
npm run compile

在IOS上可以编译成功，然后执行：npm test 测试接口成功。

在windows上编译出错，提示：error TS5042: Option 'project' cannot be mixed with source files on a command line.
于是改变思路不编译，直接安装以下模块：
npm install --save @swtc/rpc
npm install -g mocha
npm install chai --save
然后修改 test_remote.js，执行：mocha test_remote.js 测试接口成功。

![test_remote](https://user-images.githubusercontent.com/46801281/103200837-5c8a8200-4929-11eb-8a0f-29b3e0153516.png)

在测试过程中可能服务器比较慢，也可能网速比较慢，经常会提示超时。

**Comment by abellq** [comment]
测试报告，如下：
[RPC.docx](https://github.com/JCCDex/ProjectFundingProposal/files/5750304/RPC.docx)

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=A7807E08903F61C66CE06D79F23299DC5C3B20A3A75E8AEDB6FE8AA8E2CAFD29&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[审计支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=97ED8C1048F2E24F740D991015270FD6C175D2784B43C275E6F09A4703978A33&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
