### ISSUE TITLE
PFP40 chain3j升级和维护

### ISSUE THREAD

**Issue by ApisChen** [JCCDex/ProjectFundingProposal#62]
**主要想法：**
chain3j是2018年6月基于web3j替换rpc方法名版本，没有用fork方式，版本太老，两年内web3j更新了很多方法，导致现在ETH、MOAC链上的DAPP rpc部分需要写两套，为了能让ETH DAPP无缝迁移到Moac主链，建议升级chain3j版本库。

**工作内容：**
- 1. fork 最新版本web3j，不修改Java方法名，只修改rpc方法名和涉及签名部分代码，预计涉及30个接口修改工作；
- 2. 支持一年内web3j更新同步到chain3j工作；
- 3. 暂不考虑实现子链部分代码，主链版本稳定后，由我方或者子链chain3j代码提供发进行后续开发工作；

**工数预计**
- 1. 合计30日
- 2. 代码开发：15日；测试：5日；文档5日；后续升级维护：5日

**Comment by AnFengDe** [comment]
[第一次支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=07A02F2A0913870878B7AEB0A324040AB2ACE2FBB231B71E0475CADF3CBE8053&wallet=jNnZo5UFkpuNET6vbiZZ3rgFK8cuwZobz2)

**Comment by ApisChen** [comment]
已开发完毕
https://github.com/gaoshan-tech/chain3j

**Comment by lospringliu** [comment]
我来作审计， 先熟悉一下， 碰到问题再沟通

**Comment by AceLuodan** [comment]
审核，审核测试用例 代码：https://github.com/AceLuodan/chain3Jtest

**Comment by LV0404** [comment]
包名修改好了，源码编译需要切换到web3moac分支上，以前引入web3j的地方换成引web3moac就可以了其他不变

**Comment by LV0404** [comment]
钱包地址：jNnZo5UFkpuNET6vbiZZ3rgFK8cuwZobz2

**Comment by AceLuodan** [comment]
井通钱包地址： jLr6cutA646DuCEjMS6sHMew15zbfmGYKN
