### ISSUE TITLE
PFP42 分离式安全钱包

### ISSUE THREAD

**Issue by luyexunfeng** [JCCDex/ProjectFundingProposal#64]
**主要想法：**
通常的冷钱包签名总会涉及到签名后的数据的在线/无线（蓝牙等)传输的问题，这个问题的解决不但时常产生复杂的操作，且存在难以避免的安全问题。而且，通常需要专业的设备（硬件钱包）等进行操作，易用性很差。

现在有这样一种方案，就是依托于二维码传输方式进行的分离式交易，首先由一个不联网的设备进行密钥生成，然后由联网设备进行交易构造，再由不联网设备签名，然后将签名后的交易生成二维码，由联网设备进行扫码解析签名交易后广播交易。

其优点在于:
1.签名与广播分离，永远不爆露密钥于网络。
2.安全性高于通过有线或无线传输，除非直接获得签名设备，不存在通过当前技术手段远程反向破解。
3.使用方便，无需专业硬件设备，降低用户使用门槛。

流程：
B设备（联网）构建交易信息-发起交易请求-生成二维码
A设备（不联网）生成密钥-签名-扫码-解析交易请求-对请求交易签名-生成二维码
B设备（联网）扫码-解析交易数据-验证交易有效性-广播交易

总结下就是用软件钱包实现类似硬件钱包的效果和安全性。
**产品文档详见：**(https://shimo.im/docs/72877f6995fa4a88/)
**主要功能及工作量预估：**(https://shimo.im/sheets/vc8kCJHDQRjJ9rTt/0xFaj/ )

**Comment by lospringliu** [comment]
石墨应该允许匿名访问吧， 把权限设置好

**Comment by luyexunfeng** [comment]
> 石墨应该允许匿名访问吧， 把权限设置好

已设置公开。不好意思，石墨第一次用。
