### ISSUE TITLE
积分通升级+卖家端开发

### ISSUE THREAD

**Issue by baibingB** [JCCDex/ProjectFundingProposal#65]
背景介绍：
1、通过一年多的运营，取得了一定的客户，但是远远还没有达到点燃用户热情的程度；
2、经过问题分析发现目前的积分通商品种类较少，无法大量吸引用户使用，并且有很多新的想法，新的方式可以使用，特提出升级目前的积分通程序，并开发积分通卖家版。
项目概要：手持APP+服务端
使用技术：
1、APP使用跨平台HbuilderX，可同时运行至微信小程序、支付宝小程序、IOS端、Android端等
2、APP也可使用weex，前端技术制作APP直逼原生效率
3、服务端.NET编程
工作量统计
https://shimo.im/sheets/C86pVWHKr9pHQwxw/MODOC/

**Comment by baibingB** [comment]
希望得到各位领导/大神的支持

**Comment by foreso-GitHub** [comment]
现有的积分通app在运营吗？有链接吗？目前活跃用户的量大概是多少？

**Comment by baibingB** [comment]
您好！
1、目前有效持币地址2千多位，4月30至5月4活动期间，实际下单数量1956枚PG购物挖矿赠送swtc137300，目前社区刚刚成立，通过质押swtc参与一年后返还的方式加入，并实物赠送产品的方式共募集swtc7200万。社区的成立讲大大激活持币用户的参与热情。有利于下一步社区团购业务的展开
2、由于现在是自营模式产品比较单一，产品流通受限，新版本是一个开放式的平台，可以让更多通证持有者参与社区的建设，促进通证的流通，促进通证与通证，通证与实物的资产互换
3、严格意义上讲，swtc公链的上通证持有者都可以看做是积分通的潜在用户，因为积分通支持多币种的积分互换最后与实物产品的兑换，公链上的活跃用户可以看做积分通的潜在活跃用户


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JCCDex/ProjectFundingProposal"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 中午11:50
收件人:&nbsp;"JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com&gt;;
抄送:&nbsp;"泪雪"<236231765@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JCCDex/ProjectFundingProposal] 积分通升级+卖家端开发 (#65)





 
现有的积分通app在运营吗？有链接吗？目前活跃用户的量大概是多少？
