### ISSUE TITLE
开发库@swtc常规维护升级

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#67]
#### 工作量
1. 1天 三/四月份， 处理tum3，验证 PR （serializer 和 bn-plus） 
2. 1天      六月份， 同步jingtum-lib四月更新 (合约， processTx新字段)，处理多签流程的issue， 更新受影响测试用例， 更新travis/升级开发包依赖 
3. 4天     七月份， 处理多签memo的issue， 反向探索从两次hex转换切换到一次转换，重新实现多签memo， 保持json/hex/text支持和单签形式上的一致， 单元测试更新
4. 3天     八月份， 同步jingtum-lib七月/去年11月更新（ether相关，erc721， 黑名单相关），文档更新（多签需要全部改成公链实例， 跟新memo状态和实例），更新开发依赖，重新梳理单元包的依赖使便于外部独立测试
4. 1天     九月份， 处理多签转帐数量的issue

**Comment by lospringliu** [comment]
#### 全部完成
- https://github.com/swtcca/swtclib  commits + issues
- https://github.com/swtcca/swtcdoc commits
- https://swtcdoc.netlify.app

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=A42F5B16C71F1E8097FE069CEBB874B76D52F99BF63F6BCE198BC95212D13B3D&wallet=j3vyFAMQW2Ls48eoFCTsMXFq2KNWVUskSx)
