### ISSUE TITLE
墨客红包二期

### ISSUE THREAD

**Issue by lijiehelloworld** [JCCDex/ProjectFundingProposal#69]
项目概述：
墨客红包二期开发和优化。

项目内容：
主要增加2个功能：
1、erc20代币：
建议方案：
第一种：上币，社区开放申请上币的讨论板块，用户提交issues，社区审核后上币，更新到代币列表中。
		代币列表：前端页面从网络链接中获取，erc20列表，例：https://raw.githubusercontent.com/lijiehelloworld/jsontest/main/erc20.json
第二种：直接在前端代码内置相关代币信息列表。         
2、增加昵称：
建议方案：
		使用存储合约，可以将钱包地址和昵称信息关联信息放到链上，不支持上传头像。
       （如果还要支持头像，那就不适合用去中心化方案了，存储一个5kb的头像图片，大概的花费在0.1moac左右）

合计50日
需求对接整理；2日
UI和系统设计：6日；
代码开发： 29日；
测试和文档： 13日；
实际工作量会根据最终的方案有所调整。
![image](https://user-images.githubusercontent.com/44834447/100849455-8df46700-34bd-11eb-8046-23efcafaa2af.png)

**Comment by xmzhou2019** [comment]
请明确需求，技术路线和工数预计后，我好组织技术委员会投票。
