### ISSUE TITLE
PFP06 SWTC Uniapp开发短信预警平台

### ISSUE THREAD

**Issue by baibingB** [JCCDex/ProjectFundingProposal#7]
---------------------------------------------------------------------------------------------------
--项目的必要性和意义
1、激活社区现有用户，关注行情，关注井系
2、消息推送，覆盖面广，消息推送，及时准确，点对点传达
3、消息提醒，是一个成熟交易所必备工具，股票，期货合约，火币交易都有的功能，我们应该有
---------------------------------------------------------------------------------------------------
项目概要：手持APP+服务端
项目描述：1、APP端使用手机号码注册，并绑定井通账户
          2、APP端可查看井通币变化动态，类似井通钱包，提供APP与井通交互示例
		  3、APP端设定下限与上限额度
		  4、服务端如达到下限，扣除一定的井通币，自动发送短信提示到达下限可购买井通币，提供服务端与井通交互示例
		  5、服务端达到上限同样效果
		  6、服务端记录用户账号，达到用户设定提醒自动发送短信，提供与短信平台交互示例
使用技术：
		1、APP使用跨平台HbuilderX，可同时运行至微信小程序、支付宝小程序、IOS端、Android端等
		2、APP也可使用weex，前端技术制作APP直逼原生效率
		3、服务端.NET编程，同时提供CS示例
工作量统计：
https://shimo.im/sheets/BJpZTTrtYngX5d2E/

**Comment by pondem** [comment]
请补充说明该项目的必要性和意义，主要阐述该项目对生态的价值。

**Comment by Yelvabaoji** [comment]
希望可以开源到HbuilderX社区去，当作HbuilderX的例子。当然同时宣传jingtum。

**Comment by AnFengDe** [comment]
@xing136xing 给的石墨文档没法打开啊

**Comment by Yelvabaoji** [comment]
看了具体的工作量，建议把社区模块暂时去掉，重新核定工作量。

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=54BAA0BB042EBC9EC55C406B85BBF450EE682778C903AC0D07BA94DD74048375&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by lospringliu** [comment]
@xing136xing, 有进度更新吗?

**Comment by Yelvabaoji** [comment]
我现在在梳理一遍这些项目，请问，这个项目现在的进度如何？

**Comment by baibingB** [comment]
不好意思，这个项目时间有点长，现在正在调整付费接口，调整完毕后代码就可以提交------------------ 原始邮件 ------------------
发件人: "Yelvabaoji"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:45
收件人: "JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com>;
抄送: "baibingB"<236231765@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [JCCDex/ProjectFundingProposal] PFP06 SWTC Uniapp开发短信预警平台 (#7)



我现在在梳理一遍这些项目，请问，这个项目现在的进度如何？
 
&mdash;

**Comment by Yelvabaoji** [comment]
预计到什么时候完成？另外，有没有测试方法的文档？我预计需要做一点测试的吧？

**Comment by baibingB** [comment]
uniapp做的项目，接口有点麻烦，预计1到2周吧，需要什么文档一起提交到git中------------------ 原始邮件 ------------------
发件人: "Yelvabaoji"<notifications@github.com>
发送时间: 2020年3月9日(星期一) 下午4:49
收件人: "JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com>;
抄送: "baibingB"<236231765@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [JCCDex/ProjectFundingProposal] PFP06 SWTC Uniapp开发短信预警平台 (#7)



预计到什么时候完成？另外，有没有测试方法的文档？我预计需要做一点测试的吧？
 
&mdash;

**Comment by Yelvabaoji** [comment]
好的。

**Comment by baibingB** [comment]
https://gitee.com/ymhHui/Message.git
1、程序已开发完成
2、使用uniapp+C#+阿里短信+oracle数据库
3、进入程序更改阿里短息key并连接自己数据库即可

**Comment by lospringliu** [comment]
git中没有看到文档

**Comment by baibingB** [comment]
您好！
已添加说明




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xinchun Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 凌晨1:54
收件人:&nbsp;"JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com&gt;;
抄送:&nbsp;"泪雪"<236231765@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JCCDex/ProjectFundingProposal] PFP06 SWTC Uniapp开发短信预警平台 (#7)





 
git中没有看到文档

**Comment by baibingB** [comment]
您好！


已将说明提交到gitee中







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xinchun Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 凌晨1:54
收件人:&nbsp;"JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com&gt;;
抄送:&nbsp;"泪雪"<236231765@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JCCDex/ProjectFundingProposal] PFP06 SWTC Uniapp开发短信预警平台 (#7)





 
git中没有看到文档

**Comment by lospringliu** [comment]
这个我来审计

**Comment by lospringliu** [comment]
## 问答
1. 数据库 Oracle Express Edition 11g Release 2  支持吗？

**Comment by baibingB** [comment]
支持的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xinchun Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 凌晨5:27
收件人:&nbsp;"JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com&gt;;
抄送:&nbsp;"泪雪"<236231765@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JCCDex/ProjectFundingProposal] PFP06 SWTC Uniapp开发短信预警平台 (#7)





 
问答
  
数据库 Oracle Express Edition 11g Release 2  支持吗？

**Comment by lospringliu** [comment]
@baibingB 

#### 初始审计
审计人: lospringliu
审查方法
- hbuilderX 运行app（内置浏览器，手机，微信小程序模拟器）
- 测试发行h5手机版
- 测试发送短信接口和示例
审计内容:
- 立项

审计结果:
- 离立项目标还有距离，需要完善

### 具体
-  文档严重缺失，需要至少提供
> - 服务端编译要求/步骤
> - AFAT给点相关信息
> - excel如果不是必须，不要放在solution中
> - APP端配置文件需要给出相关解释
> - 例如 infoHost/exHost， 需要哪个服务/给哪个库用
> - 例如 webUrlUser/sysUser, 干什么用的， 不能让用户去猜
- 即使不做运营，功能还是需要实现的
> - 例如swt-cny的K线，显示部分被slider遮挡，需要调整。线形h5也和其它的明显不同
> - 例如首页资产详情是展示数据，但在原生应用中不显示
- 应用范围的变量已经配置了，代码中应该使用变量引用，不应该再直接用变量内容了
- 社区部分
> - 小数点太多， 可以保留到最多5位或者6位
> - 没有相关数据情况应该处理一下， 比显示`自动获取`好

### 建议
- 简化服务端， 如果希望用.net, 用.net core 替代 .net framework
- 数据库如果选用轻量级的更方便

### 后续审计
- 注册/登录
- 短信

**Comment by lospringliu** [comment]
![image](https://user-images.githubusercontent.com/9952753/85614232-b0d64180-b628-11ea-8d1d-0eddcd186bef.png)

**Comment by baibingB** [comment]
您好！


1、收到，马上调整


2、后面会使用轻量数据库和.net core跨端应用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xinchun Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月25日(星期四) 凌晨2:33
收件人:&nbsp;"JCCDex/ProjectFundingProposal"<ProjectFundingProposal@noreply.github.com&gt;;
抄送:&nbsp;"泪雪"<236231765@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [JCCDex/ProjectFundingProposal] PFP06 SWTC Uniapp开发短信预警平台 (#7)





 
@baibingB
 
初始审计
 
审计人: lospringliu
 审查方法
  
hbuilderX 运行app（内置浏览器，手机，微信小程序模拟器）
 
测试发行h5手机版
 
测试发送短信接口和示例
 审计内容:
 
立项
  
审计结果:
  
离立项目标还有距离，需要完善
  
具体
  
文档严重缺失，需要至少提供
    
服务端编译要求/步骤
 
AFAT给点相关信息
 
excel如果不是必须，不要放在solution中
 
APP端配置文件需要给出相关解释
 
例如 infoHost/exHost， 需要哪个服务/给哪个库用
 
例如 webUrlUser/sysUser, 干什么用的， 不能让用户去猜
    
即使不做运营，功能还是需要实现的
    
例如swt-cny的K线，显示部分被slider遮挡，需要调整。线形h5也和其它的明显不同
 
例如首页资产详情是展示数据，但在原生应用中不显示
    
应用范围的变量已经配置了，代码中应该使用变量引用，不应该再直接用变量内容了
 
社区部分
    
小数点太多， 可以保留到最多5位或者6位
 
没有相关数据情况应该处理一下， 比显示自动获取好
   
建议
  
简化服务端， 如果希望用.net, 用.net core 替代 .net framework
 
数据库如果选用轻量级的更方便
  
后续审计
  
注册/登录
 
短信
