### ISSUE TITLE
PFP44 井通红包DAPP

### ISSUE THREAD

**Issue by gwang74** [JCCDex/ProjectFundingProposal#71]
### 适用场景
- TokenPocket

### 支持通证
- SWT
- JMOAC
- JJCC

### 支持模式
- 均分红包
- 随机红包

### 系统架构

 - DAPP前端
 - 后台管理前端
 - 后端系统

### 技术栈
 - Egg.js、VUE、Mysql
 
### 开发计划
<table>
	<tr>
	    <th>系统</th>
	    <th>页面</th>
	    <th>功能</th>
	    <th>工时（日/人）</th>  
	</tr >
	<tr >
	    <td rowspan="9">DAPP</td>
	    <td rowspan="2">【√】创建红包页面</td>
		<td>创建红包</td>
	    <td align="right">4</td>
	</tr>
	<tr>
	    <td>红包到期退款</td>
	    <td align="right">2</td>
	</tr>
	<tr>
	    <td rowspan="2">【√】抢红包页面</td>
	    <td>口令抢红包</td>
	    <td align="right">4</td>
	</tr>
	<tr>
	    <td>红包总数</td>
	    <td align="right">1</td>
	</tr>
	<tr>
	    <td rowspan="2">【√】红包记录页面</td>
	    <td>我抢的红包列表</td>
		<td align="right">2</td>
	</tr>
	<tr>
		<td>我发的红包列表</td>
		<td align="right">2</td>
	</tr>
	<tr>
	    <td >【√】红包详情页面</td>
	    <td>红包分发列表</td>
		<td align="right">2</td>
	</tr>
        <tr>
	    <td rowspan="2">【 】我的红包统计</td>
	    <td>我抢的红包总额</td>
	    <td align="right">2</td>
	</tr>
        <tr>
	    <td>我发的红包总额</td>
	    <td align="right">2</td>
	</tr>
	<tr >
	    <td rowspan="4">后台管理</td>
	    <td rowspan="2">【 】红包页面</td>
		<td>全部红包列表</td>
	    <td align="right">2</td>
	</tr>
		<tr>
	    <td >条件查询</td>
		<td align="right">2</td>
	</tr>
		<tr>
	    <td  rowspan="2">【 】红包详情页面</td>
	    <td>红包分发列表</td>
		<td align="right">2</td>
	</tr>
	<tr>
	    <td >条件查询</td>
		<td align="right">1</td>
	</tr>
        <tr >
	    <td colspan="3" align="center">系统设计</td>
	    <td align="right">8</td>
	</tr>
        <tr >
	    <td colspan="3" align="center">UI设计</td>
	    <td align="right">8</td>
	</tr>
        <tr >
	    <td colspan="3" align="center">测试</td>
	    <td align="right">8</td>
	</tr>
	<tr >
	    <td colspan="3" align="center">交付文档</td>
	    <td align="right">2</td>
	</tr>
	<tr >
	    <td colspan="3" align="center">总计</td>
	    <td align="right">54</td>
	</tr>
</table>

**Comment by AnFengDe** [comment]
[支付50%](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=25BE1856F603F7408AD3A4C55ABE692ACAE5376085CC1175EE31FA600330AAC9&wallet=jNpN3HeKj3xHDaoruX5DKgYpyKtsAxTt4E)
[付清剩下的50%](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=9383C0C5ECC1031064C3EE8B217E349B9DD8F0AE9AAC5BAB705308180B94E5C5&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[审计工数支付](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=5C3BDFA9BF11716BE1B5B18A2CEC3B9827883C19B5D3BB15F954D866533E9922&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by gwang74** [comment]
@foreso-GitHub  @AnFengDe 
PFP44 井通红包DAPP已完成，项目开源地址如下
[DAPP前端](https://github.com/HFJingchuang/jch_candy_web)
[DAPP后台管理前端](https://github.com/HFJingchuang/red_packet_manager)
[DAPP服务端](https://github.com/HFJingchuang/red_pakcet_serve)
具体文档参照各项目README.md
