### ISSUE TITLE
PFP45 井通开发库@swtc/* 增加国密支持

### ISSUE THREAD

**Issue by lospringliu** [JCCDex/ProjectFundingProposal#73]
### 要点
- 保持现有兼容性
- 揉入现有开发包

- 工天 - 18          （**不含erc721**）

| 组件                | 内容                                                                      | 参考工时           |
| ------------- | -------------------------------------------- | ---------------- |
| 准备              | commit现有更新， 测试，作完全发布                | 1.5 |
| 设计              | 保持现有结构和兼容性                                         | 2 |
| 参考文档       |                 国密开发库                                           | 2 |
| 参考实现       |                 jingtum-lib-gm                                    | 1 |
| 代码               |                 功能实现                                               | 4 |
| 文档更新        |   说明 / 参数 / 实例                                               | 2 |
| 测试               |   测试实例及执行                                                  | 3 |
| 发布               |   发布 npm                                                             | 0.5 |
| 扩展               |   ~~同步新增TX方法~~ / 定制链支持                             | 2 |

**Comment by lospringliu** [comment]
## 进度 - 100%
1. 准备 ✅ 
> - 完成@swtc/nativescript对最新nativescript v8的支持， 修复现有测试
> - https://github.com/swtcca/swtclib/commit/257292d8d820e615f0f496c1d32fcc48700f74cb
> - https://github.com/swtcca/swtclib/commit/1ab5597770eaf2d2964e3c13d1776b17c46a8783
2. 熟悉/选择国密开发库 ✅ 
> - ~~eckey.js~~
> - sm.js ✅   -> @swtc/sm.js
> - sm3.js ✅  -> @swtc/common/SM3
> - ~~gm-crypto~~
> - ~~sm-crypto~~
3. 参考现有实现 ✅ 
> - jingtum-lib-gm ✅ 
> - jingtum-base-lib-gm ✅ 
4.  设计 ✅ 
> - 所有底层保持接口不变 address-codec/keypairs/wallet/utils/serializer/transaction ✅ 
> - 内部重构国密的支持 ✅ 
> - 高层 rpc 重构，保持接口不变 ✅ 
> - 高层 lib 优先考虑重构，保持接口不变 ✅ ~~如果碰到意料外困难，改新增 lib-gm作完全隔离~~
> - 高层 api/proxy暂不更新， 有需求时再实现
> - 删除 x-lib， 重构后 lib 和 rpc均支持所有相关公链 ✅ 
> - 扩展所有Factory接口 以支持自定制井通链 ✅ 
5.  实现 ✅ 
> - common + sm3.js ✅ 
> - address-codec ✅ 
> - keypairs + @swtc/sm.js ✅ 
> - wallet ✅ 
> - utils ✅ 
> - serializer ✅ 
> - transaction ✅
> - rpc ✅ 
> - lib ✅ 
> - ~~新增TX方法~~ erc721
> - 定制链支持 ✅ 
```
e033a42 re-arch finalize
0c6e691 (tag: @swtc/wallet@1.0.19, tag: @swtc/utils@1.0.15, tag: @swtc/transaction@1.0.21, tag: @swtc/serializer@1.0.16, tag: @swtc/rpc@1.0.10, tag: @swtc/proxy@1.0.20, tag: @swtc/lib@1.0.18, tag: @swtc/keypairs@1.0.17, tag: @swtc/common@1.0.23, tag: @swtc/api@1.0.15, tag: @swtc/address-codec@1.0.16) chore(release): publish
a7f1658 re-arch to support private chains and test updates
c75cc45 add npm run test:guomi and retire x-lib
596e6e3 lib + rpc higher level support tests
f946a3a lib + rpc higher level support
d3ec844 above implements key types d25519 + secp256k1 + sm2p256v1
455fcf2 utils + serializer + transaction middle level support
6d0b985 address-codec + keypairs + wallet lower level tests
ffa4ff7 address-codec + keypairs + wallet lower level support
6de06d1 common + sm.js + sm3.js
```
6.  测试 (node.js v12) ✅ 
> - `git clone git@github.com:swtcca/swtclib.git`
> - cd swtclib; npm install
> - npm run test:guomi
> - npm run test:guomiapi
7. 文档 - ✅ 
> - https://swtcdoc.netlify.app
> - https://swtcdoc.netlify.app/docs/swtcxlib/
8.  发布 ✅

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=4BAA718FA0DF32F05492AB96210A517DCCAA4AED080A8BF315A56558D9981C61&wallet=j3vyFAMQW2Ls48eoFCTsMXFq2KNWVUskSx)
