### ISSUE TITLE
PFP46 井通java开发包支持国密SM2、SM3算法

### ISSUE THREAD

**Issue by xdjiang** [JCCDex/ProjectFundingProposal#74]
**jcc_jingtum_java**
版本库地址: https://github.com/JCCDex/jcc_jingtum_java
1:生成hash的算法替换成SM3算法
2:签名算法替换成SM2算法

**jcc_wallet**
版本库地址:https://github.com/JCCDex/jcc_wallet_java
1:创建钱包的算法需要替换成SM2算法

**Comment by AnFengDe** [comment]
[支付记录](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=EFBE4BB8BDF69FC6ABAABCC776280876D1B1D63649D23DDA0BFB438DDC9639D8&wallet=jHEnnKkRcws7sm7kt4hLyKfmhkx6U58Gn)
