### ISSUE TITLE
PFP47 基于墨客联盟公链的电子签章系统

### ISSUE THREAD

**Issue by lijiehelloworld** [JCCDex/ProjectFundingProposal#75]
概述：
本项目是基于MOAC联盟公链开发一套电子签章系统，丰富MOAC联盟链生态系统。

系统功能：
1.基于区块链的企业DID身份生产颁发，
2.基于区块链的企业签章合约、身份合约、合同合约。
3.企业用户用于基于ECDSA算法对合同签名，并数据上链。
4.不同文件格式的合同文件转换成PDF和预览，以及在pdf上将签名数据转换为可视的印章图像。
5.支持用户基于区块链上的数据直接合约合同的签署情况。
6.基于中心化服务的证书保存和管理平台。
7.其他：如通知，帮助文档等辅助功能。

项目产出：
1、H5客户端（适配PC和手机，注册、生成保管公私钥、上传预览合同、合同签名、合同核验等）。
2、客户端接口服务（注册、认证、签章合约部署、文件服务、链上数据统计、托管加密后私钥等）。
3、管理后台（用户管理、合约管理、合同管理、图表统计等）。
4、管理后台接口服务（用户管理、合约管理、合同管理、图表统计等）。
5、智能合约：签章合约、身份合约、合同合约等。
后端采用Java+Spring Boot框架、前端VUE框架，前后端分离模式开发。

工作量：
1.UI设计：20人日，其中客户端10人日、管理后台10人日；
2.开发：255人日，其中客户端 120人日、接口服务 60人日、管理后台 40人日、管理后台接口20人日、智能合约15人日；
3.测试：40人日
4.管理：20人日
合计：335人日

**Comment by JCCDex** [comment]
你这个工作范围太粗了，能给出到画面级别的工作清单吗？不然我不太好估计工数

**Comment by ApisChen** [comment]
[平台功能清单概述.xlsx](https://github.com/JCCDex/ProjectFundingProposal/files/7118017/default.xlsx)

**Comment by ApisChen** [comment]
基于墨客联盟链的电子签章系统，核心技术模块为用户/企业身份凭证（W3C DID和VC）下发、签章管理、合同签署、合同核验。具体系统交互时序图https://kdocs.cn/l/cmC9p9DGC0OK。

本次提案开源模块：

- 智能合约：1. DID合约（机构、用户身份凭证）；2. 签章合约（企业签章管理）；3. 合同合约（签署合同上链存证）；
- 服务端合约调用：根据业务场景，智能合约合约接口调用，Java实现；
- 客户端合同签署核验：合同签署、核验等功能，JS实现；

工作量合计110人日，具体见：https://kdocs.cn/l/caG7q8la70lC

成果验收，主要是源码、文档、可运行demo，都在工作量表格中。

**Comment by AnFengDe** [comment]
[第一次30%](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=2A17413E5C965BA5A0959F0E2FBD4FF41C99A9C338041E98EC72BE86B93136D1&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[第二次支付30%](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=CF487EAF3228CD799B5BB7E20BCA1FD85E72DFDEC87899C7941861FDE8F461DC&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[第三次付清](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=FF9509002DDB0BF9EC6AE7A62037B1DB3F6336A265F51B04FAFA783A818EF877&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)
[支付审计费用](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=05E15C742777132D64EDE7D780E8CE0A8500BEAC53E46F8347C8799C54BCC185&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

**Comment by ApisChen** [comment]
项目提交：https://github.com/gaoshan-tech/sealcontract

**Comment by gwang74** [comment]
### 审计报告

#### 合约部署

- 工具：[REMIX](http://remix.app.hubwiz.com/) && MetaMask Chrome插件
- 网络：[Ropsten (3) network](https://ropsten.etherscan.io/)
- 账号：0xDaedB24703a417136C368cb4266d77609F7a893A

#### 合约审计

- [身份合约](https://github.com/gaoshan-tech/sealcontract/blob/master/%E5%90%88%E7%BA%A6%E4%BB%A3%E7%A0%81/Identity.sol)

​		1、部署实现合约：[0xdB67F5ABa085347E4eFBF45E89d12Aae41AFBE2a](https://ropsten.etherscan.io/tx/0x2e1a656b23efe82cb17376e15be54830de66a84a91038fb05c5331384a25f38d)

​		2、部署代理合约：[0x1b4892e9395cDCD49173eC3A0EFE5D78727C95a1](https://ropsten.etherscan.io/tx/0xb49fed1c246e1a55d03c77ca3da0db0ea17f87f171ec96cb309b4e5ee6207f01)

​		3、功能测试：

​				-	[初始化owner](https://ropsten.etherscan.io/tx/0x41cbc44f41c5523efb4e28f9c3fb7c512a5182f4652140a19d71cc4416305658)	✅

​				-	[禁止重复初始化owner](https://ropsten.etherscan.io/tx/0xd985e32a05b6bb83bd7313411a7166b8eaba912a9a998636d6d2c358b68e07e3)	✅	

​				-	[允许转移owner](https://ropsten.etherscan.io/tx/0xa6345c5865b7e393994fe85194f26490360f832e180ed0142bf12d4d18ef7c72)	✅

​				-	[添加身份](https://ropsten.etherscan.io/tx/0x734fab1dbaf099238339ae1b68cf0ef45b57570b9616fe4b741ca9730b3d901a)	✅

​				-	[禁止重复添加身份](https://ropsten.etherscan.io/tx/0xa573ae1aacf8eeaaa31171ff90103e2b7d1edb70dcd7cac33cd62037d7bcdadb)	✅

​				-	[吊销身份](https://ropsten.etherscan.io/tx/0xb5918173e5104375275d538a24fcf298c72858080c1ec56634d1b533d314cce8)	✅

​				-	[禁止重复吊销身份](https://ropsten.etherscan.io/tx/0xc7df0795e5edf7279e459108c3093af64d375cdd8789d1d9f8d61edfb04538d0)	✅

​				-	查询身份有效性	✅

​				-	查询身份吊销时间	✅

​				-	[允许重新添加已吊销身份&&身份有效性确认](https://ropsten.etherscan.io/tx/0x40e6570cf15ce4dffc23f56d9236e63eec4f1a3a24cd210f092c9ccd6ddc3c97)	✅

​				-	禁止非owner账号操作(添加/吊销身份)	✅

​				-	支持合约升级 	✅

- [签章路由合约](https://github.com/gaoshan-tech/sealcontract/blob/master/%E5%90%88%E7%BA%A6%E4%BB%A3%E7%A0%81/SealsRouter.sol)

1、部署实现合约：[0xF9Fa9C0D7f6952C32c13b26783Dc33CDbED3c8eC](https://ropsten.etherscan.io/tx/0xf34659b319e8bacfd84532105d9f0f2962e440a3296dd5bab62f90fdcaef88db)

2、部署代理合约：[0x71c8F13b96Bb20e1F4EF592d3da87854e10b771D](https://ropsten.etherscan.io/tx/0xc3c6ac3e4c804755645607b55b307d1ab0c7dd75621c306b27b87854e0040797)

​3、功能测试：

​				-	[初始化owner](https://ropsten.etherscan.io/tx/0xb1d21238dcc28f39a437f2eb89fa9c32d60e47cf85e2839095907939c86cf6a4)	✅

​				-	[禁止重复初始化owner](https://ropsten.etherscan.io/tx/0xfe7d8d18ebfec033cd726fd86e02e3386ac45085211ef349fa9b8da0a1289434)	✅	

​				-	[允许转移owner](https://ropsten.etherscan.io/tx/0x3cdfa41d315316eb9a158d45c17c21e354bce5b439219f1d82d27a7d9374356f)	✅

​				-	[创建企业签章合约](https://ropsten.etherscan.io/tx/0x05d756894527896cf668f24d1f873bdca3204876ba5be43534ff1bbda7141985)	✅

​				-	查询指定索引的签章合约地址	✅

​				- 	查询指定法人和企业识别码的企业签章合约地址	✅

​				-	预计算签章合约地址与实际地址匹配	✅

​				-	查询签章合约owner	✅

​				-	查询签章合约状态	✅

​				-	[管理员吊销企业签章合约](https://ropsten.etherscan.io/tx/0x5d131e814ca2c34dc4350e3dd6f8342bdccb8b656339250dce790dfdf9e22a6b)	✅

​				-	查询签章合约吊销后的相关状态	❗️（签章合约吊销后仍可执行授权）

​				-	[允许带签名的企业签章合约授权](https://ropsten.etherscan.io/tx/0x3d98499c143acb95b06b44510c8f45cb794f7d9ea5f83f1a8c35b9f97d2e4a9f)	✅

​				-	[允许带签名的企业签章合约吊销授权](https://ropsten.etherscan.io/tx/0x48e70fffa20ed13cf6b57f6da5f2307a742fc7ab940592fa319ef32ec722aaa8)	✅

​				-	禁止授权签名重复使用	✅

​				-	禁止非owner账号操作(不带签名的企业签章授权/吊销)	✅

​				-	支持合约升级 	✅

- [合同合约](https://github.com/gaoshan-tech/sealcontract/blob/master/%E5%90%88%E7%BA%A6%E4%BB%A3%E7%A0%81/Contracts.sol)

​		1、部署实现合约：[0x5C6D26949B3Ed382CCa9eE5E58218987f70F3c61](https://ropsten.etherscan.io/tx/0x8749585ad66930e1488dfce11e519f8f2f097234dc3e7c62a00314746714bd1e)

​		2、部署代理合约：[0xF9398CdCD15f527681D309066465AAB8fD8148Ac](https://ropsten.etherscan.io/tx/0x8c6868eacc088b070763a8d6dde77b3c2747077a009ed58ba0d5a96348c57511)

​		3、功能测试：

​				-	[初始化owner](https://ropsten.etherscan.io/tx/0x3e8824a35f39e3a7f5ece4146d7fbb36cecbe4811d864c58455833a42d077bc1)	✅

​				-	[禁止重复初始化owner](https://ropsten.etherscan.io/tx/0x7846355d25760cfdbcefd5b50ffec623844558bc3a9964834c1f59318e2af144)	✅	

​				-	[允许转移owner](https://ropsten.etherscan.io/tx/0xe8d360648c06409f26bc858eb9f6527d3ef7d08f58fde988182a6b3050ce48dc)	✅

​				-	[设置签章路由合约](https://ropsten.etherscan.io/tx/0x2445c73cad3b0f05d93b6afe659c81c9f1812a76abc4f105dbf8449e41b51f19)	✅

​				-	[禁止使用已吊销签章的合同上链](https://ropsten.etherscan.io/tx/0xdc6e1c979d4209649d83079a9154e08da6f755208e499f3e6bd02190990a3968)	✅

​				- 	[禁止使用未授权签章的合同上链](https://ropsten.etherscan.io/tx/0xcfedb24d5343a6e7f103302a287d0fbac9c416c55e5718ea6a76c55c813ea33e)	✅

​				-	[合同上链](https://ropsten.etherscan.io/tx/0xd88e180468f25b73bd123e59ec3bf6ba5557c3baf4e78d4119cee6a8321d8352)	✅

​				-	查询合同是否已上链	✅

​				-	查询指定合同上链信息	✅

​				-	查询合同上链时间	✅

​				-	禁止非owner账号操作(设置签章路由合约)	✅

​				-	支持合约升级 	✅

#### 审计结果

1、签章路由合约在吊销签章合约后，该签章合约仍可以执行授权等操作（但在合同合约内校验了签章有效性），是否考虑将路由合约内的签章状态列表改为由签章合约存储状态并在操作时追加校验；

2、合同合约内引入`SafeMath.sol`,但并未使用；`UpgradeabilityProxy.sol`未引入`Address.sol`

3、其他功能测试均通过；

**Comment by lijiehelloworld** [comment]
对于审计结果进行一个补充说明：
1、设计基于2点考虑：
      第一签章合约创建后，我们希望权利完全属于用户，平台也无权修改用户合约的任何数据，
      第二考虑未来扩展性，签章合约也可以用第三方甚至用户自己创建，这样平台也不方便操作用户的合约。
      平台只在路由合约中对于认证和吊销，进行背书，相关服务也会去路由合约去验证签章合约的有效性。
2、SafeMath.sol引入未使用,UpgradeabilityProxy.sol未引入Address.sol    -----已修改,最新代码已提交。
                 -
