### ISSUE TITLE
PFP49 井通开发库java版本(jcc_jingtum_java和jcc_wallet_java)增加国密支持 PFP/资助项目提案

### ISSUE THREAD

**Issue by xdjiang** [JCCDex/ProjectFundingProposal#76]
### 要点
- 保持现有兼容性
- 揉入现有开发包

- 工天 - 18.5        

| 组件                | 内容                                                                      | 参考工时           |
| ------------- | -------------------------------------------- | ---------------- |
| 准备              | 了解jcc_jingtum_java和jcc_wallet_java代码                 | 3 |
| 参考实现       |                 swtc-lib                                                          | 2 |
| 代码               |                 功能实现                                                        | 5 |
| 代码整理       |   jcc_jingtum_java签名部分迁移到jcc_wallet_java       | 4 |
| 文档更新        |   说明 / 参数 / 实例                                                        | 2 |
| 测试               |   测试实例及执行                                                           | 2 |
| 发布               |   发布 maven中央库                                                      | 0.5 |

**Comment by AnFengDe** [comment]
合并到[#74 ]
