### ISSUE TITLE
PFP08 JCC_RPC_易语言开发实现

### ISSUE THREAD

**Issue by haohant** [JCCDex/ProjectFundingProposal#9]
目标： 实现一个易语言版的JCC_RPC包装库及一个可自动交易的下单程序模块
理由：1.当前最简单的开发语言，无编程基础1天可入门
           2.易语言在国内的基础庞大，吸引更多有兴趣的人员加入开发序列，便于社区成员转化
开发内容及工作量：https://shimo.im/sheets/ZBM2DGG7mkY8et3N/
目标库：https://github.com/JCCDex/jcc_rpc_yi

**Comment by Yelvabaoji** [comment]
做完了能够开源到易语言的社区去吗？毕竟里面有jingtum

**Comment by AnFengDe** [comment]
是的，接受资助的前提是开源

**Comment by haohant** [comment]
必须开源的呀，目前各种语言中界面化最快的就是易了，虽然比较LOW，但是门槛低，速度快。
对社区成员来说，有了一个易用工具，可以尝试开发；对于易社区来说，有一个介入区块链的入口。

**Comment by AnFengDe** [comment]
[支付50% ](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=A13117FEC4C611D97049AE196E34A8766F85B8AB85F2C33F3496630046E77972&wallet=jB24RRYtoXViU3Gxvki6xZYK9PaaTjG5MY)

[支付剩余50%](https://swtcscan.jccdex.cn/#/trade/tradeDetail/?hash=E1C3DFCE20554642575DF41ED323F7D41D2FEFA17156BD13F3976EEFC70E0737&wallet=jUZbcmSWGy2dUYoaz6xDi7imPSbMJpJP7T)
